//! Event types for WebSocket communication between server, web clients, and
//! daemon.
//!
//! Wire stability: these strings are part of the client contract. Renaming a
//! value is a breaking change.

// Issue events
pub const EVENT_ISSUE_CREATED: &str = "issue:created";
pub const EVENT_ISSUE_UPDATED: &str = "issue:updated";
pub const EVENT_ISSUE_DELETED: &str = "issue:deleted";
pub const EVENT_ISSUE_METADATA_CHANGED: &str = "issue_metadata:changed";
pub const EVENT_ISSUE_ATTACHMENTS_CHANGED: &str = "issue_attachments:changed";
pub const EVENT_DEPENDENCY_GRAPH_UPDATED: &str = "dependency_graph:updated";

// Comment events
pub const EVENT_COMMENT_CREATED: &str = "comment:created";
pub const EVENT_COMMENT_UPDATED: &str = "comment:updated";
pub const EVENT_COMMENT_DELETED: &str = "comment:deleted";
pub const EVENT_COMMENT_RESOLVED: &str = "comment:resolved";
pub const EVENT_COMMENT_UNRESOLVED: &str = "comment:unresolved";
pub const EVENT_REACTION_ADDED: &str = "reaction:added";
pub const EVENT_REACTION_REMOVED: &str = "reaction:removed";
pub const EVENT_ISSUE_REACTION_ADDED: &str = "issue_reaction:added";
pub const EVENT_ISSUE_REACTION_REMOVED: &str = "issue_reaction:removed";

// Agent events
pub const EVENT_AGENT_STATUS: &str = "agent:status";
pub const EVENT_AGENT_CREATED: &str = "agent:created";
pub const EVENT_AGENT_ARCHIVED: &str = "agent:archived";
pub const EVENT_AGENT_RESTORED: &str = "agent:restored";

// Task events (server <-> daemon). Each event maps to a status transition on
// agent_task_queue. Front-end subscribes by `task:` prefix and invalidates
// the workspace task snapshot, so the granularity here is "what does the user
// want to see change" — not "every internal status flip".
pub const EVENT_TASK_QUEUED: &str = "task:queued"; // ∅ → queued (enqueue / retry create)
pub const EVENT_TASK_DISPATCH: &str = "task:dispatch"; // queued → dispatched (daemon claim)
pub const EVENT_TASK_RUNNING: &str = "task:running"; // dispatched → running (daemon started)
pub const EVENT_TASK_WAITING_LOCAL_DIRECTORY: &str = "task:waiting_local_directory"; // dispatched → waiting_local_directory
pub const EVENT_TASK_PROGRESS: &str = "task:progress";
pub const EVENT_TASK_COMPLETED: &str = "task:completed"; // running → completed
pub const EVENT_TASK_FAILED: &str = "task:failed"; // running → failed
pub const EVENT_TASK_MESSAGE: &str = "task:message";
pub const EVENT_TASK_CANCELLED: &str = "task:cancelled"; // * → cancelled

// Inbox events
pub const EVENT_INBOX_NEW: &str = "inbox:new";
pub const EVENT_INBOX_READ: &str = "inbox:read";
pub const EVENT_INBOX_UNREAD: &str = "inbox:unread";
pub const EVENT_INBOX_ARCHIVED: &str = "inbox:archived";
pub const EVENT_INBOX_UNARCHIVED: &str = "inbox:unarchived";
pub const EVENT_INBOX_BATCH_READ: &str = "inbox:batch-read";
pub const EVENT_INBOX_BATCH_ARCHIVED: &str = "inbox:batch-archived";

// Workspace events
pub const EVENT_WORKSPACE_UPDATED: &str = "workspace:updated";
pub const EVENT_WORKSPACE_DELETED: &str = "workspace:deleted";

// Member events
pub const EVENT_MEMBER_ADDED: &str = "member:added";
pub const EVENT_MEMBER_UPDATED: &str = "member:updated";
pub const EVENT_MEMBER_REMOVED: &str = "member:removed";

// Subscriber events
pub const EVENT_SUBSCRIBER_ADDED: &str = "subscriber:added";
pub const EVENT_SUBSCRIBER_REMOVED: &str = "subscriber:removed";

// Activity events
pub const EVENT_ACTIVITY_CREATED: &str = "activity:created";

// Skill events
pub const EVENT_SKILL_CREATED: &str = "skill:created";
pub const EVENT_SKILL_UPDATED: &str = "skill:updated";
pub const EVENT_SKILL_DELETED: &str = "skill:deleted";

// Chat events
pub const EVENT_CHAT_MESSAGE: &str = "chat:message";
pub const EVENT_CHAT_DONE: &str = "chat:done";
/// Supplements a finished turn with follow-up suggestions generated by the
/// post-completion pass. Sent after chat:done; clients that don't know it
/// simply never resolve the (equally unknown) pending state.
pub const EVENT_CHAT_QUICK_ACTIONS: &str = "chat:quick_actions";
/// Carries the deferred outcome of a cancelled chat task once the daemon has
/// flushed its Agent event history (or the sweeper grace period expired): either a
/// late "Stopped." assistant message or a draft restore (#5219). Channel
/// outbounds (Slack/Lark) deliberately do not subscribe to it — cancellation
/// stays silent on external channels.
pub const EVENT_CHAT_CANCEL_FINALIZED: &str = "chat:cancel_finalized";
pub const EVENT_CHAT_SESSION_READ: &str = "chat:session_read";
pub const EVENT_CHAT_SESSION_DELETED: &str = "chat:session_deleted";
pub const EVENT_CHAT_SESSION_UPDATED: &str = "chat:session_updated";

// In-app workspace channel events. These are workspace-scoped broadcasts;
// the payload contains the authoritative row so clients can invalidate or
// reconcile without treating external IM integrations as the same feature.
pub const EVENT_CHANNEL_CREATED: &str = "channel:created";
pub const EVENT_CHANNEL_MESSAGE_CREATED: &str = "channel:message";

// Project events
pub const EVENT_PROJECT_CREATED: &str = "project:created";
pub const EVENT_PROJECT_UPDATED: &str = "project:updated";
pub const EVENT_PROJECT_DELETED: &str = "project:deleted";
pub const EVENT_PROJECT_RESOURCE_CREATED: &str = "project_resource:created";
pub const EVENT_PROJECT_RESOURCE_UPDATED: &str = "project_resource:updated";
pub const EVENT_PROJECT_RESOURCE_DELETED: &str = "project_resource:deleted";

// Label events
pub const EVENT_LABEL_CREATED: &str = "label:created";
pub const EVENT_LABEL_UPDATED: &str = "label:updated";
pub const EVENT_LABEL_DELETED: &str = "label:deleted";
pub const EVENT_ISSUE_LABELS_CHANGED: &str = "issue_labels:changed";

// Custom property events. Definitions are archived, never deleted, so there
// is no property:deleted — archive arrives as property:updated.
pub const EVENT_PROPERTY_CREATED: &str = "property:created";
pub const EVENT_PROPERTY_UPDATED: &str = "property:updated";
pub const EVENT_ISSUE_PROPERTIES_CHANGED: &str = "issue_properties:changed";

/// ONE event for all four issue-status-catalog writes (PB-6243) — create,
/// edit, archive, reorder — because the catalog is read as a whole table and
/// every client answers all four the same way: re-read it. The `action` in
/// the payload is advisory; nothing routes on it.
pub const EVENT_ISSUE_STATUS_CHANGED: &str = "issue_status:changed";

// Pin events
pub const EVENT_PIN_CREATED: &str = "pin:created";
pub const EVENT_PIN_DELETED: &str = "pin:deleted";
pub const EVENT_PIN_REORDERED: &str = "pin:reordered";

// Invitation events
pub const EVENT_INVITATION_CREATED: &str = "invitation:created";
pub const EVENT_INVITATION_ACCEPTED: &str = "invitation:accepted";
pub const EVENT_INVITATION_DECLINED: &str = "invitation:declined";
pub const EVENT_INVITATION_REVOKED: &str = "invitation:revoked";

// Automation events
pub const EVENT_AUTOMATION_CREATED: &str = "automation:created";
pub const EVENT_AUTOMATION_UPDATED: &str = "automation:updated";
pub const EVENT_AUTOMATION_DELETED: &str = "automation:deleted";
pub const EVENT_AUTOMATION_RUN_START: &str = "automation:run_start";
pub const EVENT_AUTOMATION_RUN_DONE: &str = "automation:run_done";

// Team events
pub const EVENT_TEAM_CREATED: &str = "team:created";
pub const EVENT_TEAM_UPDATED: &str = "team:updated";
pub const EVENT_TEAM_DELETED: &str = "team:deleted";

// Daemon events
pub const EVENT_DAEMON_HEARTBEAT: &str = "daemon:heartbeat";
pub const EVENT_DAEMON_HEARTBEAT_ACK: &str = "daemon:heartbeat_ack";
pub const EVENT_DAEMON_REGISTER: &str = "daemon:register";
pub const EVENT_DAEMON_TASK_AVAILABLE: &str = "daemon:task_available";
pub const EVENT_DAEMON_RUNTIME_PROFILES_CHANGED: &str = "daemon:runtime_profiles_changed";
pub const EVENT_DAEMON_WORKSPACES_CHANGED: &str = "daemon:workspaces_changed";
/// A runtime-scoped hint that a heartbeat-carried request (today: model-list
/// discovery) is queued for that runtime. The hint carries no work itself:
/// the daemon still pulls through the normal heartbeat claim, so a lost or
/// duplicated hint is harmless (PB-5444).
pub const EVENT_DAEMON_PENDING_WORK: &str = "daemon:pending_work";
/// Generic daemon→server request/response over the WebSocket control
/// connection (PB-4257): correlation id + method + body, replied with the
/// same request id. Transport for WS-first claim (with HTTP fallback).
pub const EVENT_DAEMON_RPC_REQUEST: &str = "daemon:rpc_request";
pub const EVENT_DAEMON_RPC_RESPONSE: &str = "daemon:rpc_response";

// GitHub integration events
pub const EVENT_GITHUB_INSTALLATION_CREATED: &str = "github_installation:created";
pub const EVENT_GITHUB_INSTALLATION_DELETED: &str = "github_installation:deleted";
pub const EVENT_PULL_REQUEST_LINKED: &str = "pull_request:linked";
pub const EVENT_PULL_REQUEST_UPDATED: &str = "pull_request:updated";
pub const EVENT_PULL_REQUEST_UNLINKED: &str = "pull_request:unlinked";

// VCS integration events (Forgejo / Gitea / GitLab)
pub const EVENT_VCS_CONNECTION_CREATED: &str = "vcs_connection:created";
pub const EVENT_VCS_CONNECTION_DELETED: &str = "vcs_connection:deleted";

// Lark integration events. `created` covers both first-install and
// re-install via UpsertLarkInstallation; `revoked` flips status to 'revoked'
// without deleting the row so the audit trail is preserved.
pub const EVENT_LARK_INSTALLATION_CREATED: &str = "lark_installation:created";
pub const EVENT_LARK_INSTALLATION_REVOKED: &str = "lark_installation:revoked";

// Slack installation lifecycle (PB-3666). Same semantics as the Lark pair.
pub const EVENT_SLACK_INSTALLATION_CREATED: &str = "slack_installation:created";
pub const EVENT_SLACK_INSTALLATION_REVOKED: &str = "slack_installation:revoked";

// DingTalk installation lifecycle follows the same create/revoke semantics as
// Slack's BYO channel installation. BindingUpdated shares the
// dingtalk_installation prefix because it changes the member-scoped account
// identifiers returned by the installation listing.
pub const EVENT_DINGTALK_INSTALLATION_CREATED: &str = "dingtalk_installation:created";
pub const EVENT_DINGTALK_INSTALLATION_REVOKED: &str = "dingtalk_installation:revoked";
pub const EVENT_DINGTALK_ACCOUNT_BINDING_UPDATED: &str = "dingtalk_installation:binding_updated";
pub const EVENT_DINGTALK_GROUP_ROUTE_UPDATED: &str = "dingtalk_group_route:updated";

// WeCom smart-bot installation lifecycle. Same semantics as Lark / Slack.
pub const EVENT_WECOM_INSTALLATION_CREATED: &str = "wecom_installation:created";
pub const EVENT_WECOM_INSTALLATION_REVOKED: &str = "wecom_installation:revoked";

// Telegram installation lifecycle. Same contract as the Slack pair.
pub const EVENT_TELEGRAM_INSTALLATION_CREATED: &str = "telegram_installation:created";
pub const EVENT_TELEGRAM_INSTALLATION_REVOKED: &str = "telegram_installation:revoked";

// Personal WeChat iLink installation lifecycle (distinct from WeCom).
pub const EVENT_WEIXIN_INSTALLATION_CREATED: &str = "weixin_installation:created";
pub const EVENT_WEIXIN_INSTALLATION_REVOKED: &str = "weixin_installation:revoked";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wire_values_are_byte_stable() {
        assert_eq!(EVENT_ISSUE_CREATED, "issue:created");
        assert_eq!(EVENT_TASK_QUEUED, "task:queued");
        assert_eq!(
            EVENT_TASK_WAITING_LOCAL_DIRECTORY,
            "task:waiting_local_directory"
        );
        assert_eq!(EVENT_CHAT_QUICK_ACTIONS, "chat:quick_actions");
        assert_eq!(EVENT_CHAT_CANCEL_FINALIZED, "chat:cancel_finalized");
        assert_eq!(EVENT_CHANNEL_CREATED, "channel:created");
        assert_eq!(EVENT_CHANNEL_MESSAGE_CREATED, "channel:message");
        assert_eq!(EVENT_INBOX_BATCH_READ, "inbox:batch-read");
        assert_eq!(EVENT_DAEMON_PENDING_WORK, "daemon:pending_work");
        assert_eq!(EVENT_DAEMON_RPC_REQUEST, "daemon:rpc_request");
        assert_eq!(EVENT_ISSUE_STATUS_CHANGED, "issue_status:changed");
        assert_eq!(
            EVENT_DINGTALK_ACCOUNT_BINDING_UPDATED,
            "dingtalk_installation:binding_updated"
        );
    }
}
