[package]
name = "cordy-middleware"
description = "HTTP middleware"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true }
cordy-auth = { path = "../cordy-auth" }
cordy-db = { path = "../cordy-db" }
cordy-redis = { path = "../cordy-redis" }
chrono = { workspace = true }
ipnetwork = { workspace = true }
jsonwebtoken = { workspace = true }
redis = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
