//! Historical migration index map.
//!
//! Entries for old schema objects intentionally mirror immutable migration
//! filenames and relation names. They are migration-runner compatibility data,
//! not runtime product identifiers. Keep them until the final schema rename is
//! deployed everywhere and the corresponding pre-rename rollback window is
//! retired; never use these names in new application code.

pub(crate) const CONCURRENT_INDEX_CLEANUPS_UP: &[(&str, &str)] = &[
    (
        "035_task_queue_issue_id_index",
        "idx_agent_task_queue_issue_id",
    ),
    (
        "067_task_queue_claim_candidate_index",
        "idx_agent_task_queue_claim_candidates",
    ),
    (
        "074_task_usage_updated_at_index",
        "idx_task_usage_updated_at",
    ),
    (
        "075_task_usage_created_at_index",
        "idx_task_usage_created_at",
    ),
    (
        "078_task_usage_created_at_legacy_index",
        "idx_task_usage_created_at_legacy",
    ),
    (
        "080_agent_task_queue_queued_index",
        "idx_agent_task_queue_queued_created_at",
    ),
    (
        "106_member_user_workspace_index",
        "idx_member_user_workspace",
    ),
    (
        "114_agent_task_queue_running_started_at_index",
        "idx_agent_task_queue_running_started_at",
    ),
    (
        "115_agent_runtime_last_seen_at_index",
        "idx_agent_runtime_last_seen_at",
    ),
    ("119_user_created_at_index", "idx_user_created_at"),
    (
        "125_agent_task_queue_dispatched_prepare_index",
        "idx_agent_task_queue_dispatched_prepare",
    ),
    ("135_comment_workspace_index", "idx_comment_workspace"),
    ("138_issue_title_trgm_index", "idx_issue_title_trgm"),
    (
        "139_issue_description_trgm_index",
        "idx_issue_description_trgm",
    ),
    ("140_comment_content_trgm_index", "idx_comment_content_trgm"),
    ("141_project_title_trgm_index", "idx_project_title_trgm"),
    (
        "142_project_description_trgm_index",
        "idx_project_description_trgm",
    ),
    (
        "143_agent_task_queue_chat_pending_v2",
        "idx_agent_task_queue_chat_pending_v2",
    ),
    (
        "153_chat_pinned_agent_user_ws_index",
        "idx_chat_pinned_agent_user_ws",
    ),
    ("156_chat_session_pinned_index", "idx_chat_session_pinned"),
    (
        "160_chat_message_input_owner_index",
        "idx_chat_message_input_owner",
    ),
    ("165_attachment_task_id_index", "idx_attachment_task"),
    (
        "167_resource_label_namespace_index",
        "issue_label_workspace_type_name_lower_idx",
    ),
    (
        "168_resource_label_type_index",
        "issue_label_workspace_type_idx",
    ),
    ("169_agent_label_lookup_index", "agent_to_label_label_idx"),
    ("170_skill_label_lookup_index", "skill_to_label_label_idx"),
    (
        "172_agent_system_identity_index",
        "agent_system_identity_unique",
    ),
    (
        "177_autopilot_run_webhook_delivery_index",
        "uq_autopilot_run_webhook_delivery",
    ),
    (
        "178_webhook_delivery_queue_index",
        "idx_webhook_delivery_queue",
    ),
    (
        "181_task_chat_finalize_deferred_index",
        "idx_task_chat_finalize_deferred",
    ),
    (
        "183_chat_draft_restore_index",
        "idx_chat_draft_restore_session",
    ),
    (
        "187_autopilot_rule_version_index",
        "idx_autopilot_rule_version_active",
    ),
    ("192_issue_properties_gin_index", "idx_issue_properties_gin"),
    (
        "194_issue_property_workspace_name_index",
        "idx_issue_property_ws_name",
    ),
    (
        "195_issue_property_workspace_index",
        "idx_issue_property_workspace",
    ),
    (
        "200_inbox_archived_listing_index",
        "idx_inbox_recipient_archived_created",
    ),
    (
        "201_inbox_active_by_issue_index",
        "idx_inbox_active_by_issue",
    ),
    (
        "203_issue_workspace_assignee_index",
        "idx_issue_workspace_assignee",
    ),
    (
        "204_issue_workspace_parent_index",
        "idx_issue_workspace_parent",
    ),
    (
        "205_issue_workspace_position_index",
        "idx_issue_workspace_position",
    ),
    (
        "208_client_usage_daily_unique_index",
        "client_usage_daily_identity_date_uidx",
    ),
    (
        "210_client_usage_daily_query_index",
        "client_usage_daily_activity_client_user_idx",
    ),
    (
        "211_client_usage_daily_workspace_index",
        "client_usage_daily_workspace_idx",
    ),
    ("215_chat_session_project_index", "idx_chat_session_project"),
    (
        "217_vcs_connection_workspace_index",
        "idx_vcs_connection_workspace",
    ),
    (
        "218_vcs_pull_request_workspace_index",
        "idx_vcs_pull_request_workspace",
    ),
    (
        "219_vcs_pull_request_connection_index",
        "idx_vcs_pull_request_connection",
    ),
    (
        "220_issue_vcs_pull_request_pr_index",
        "idx_issue_vcs_pull_request_pr",
    ),
    (
        "221_vcs_commit_status_lookup_index",
        "idx_vcs_commit_status_lookup",
    ),
    (
        "223_github_pr_check_run_pr_ordinal_index",
        "github_pull_request_check_run_pr_ordinal_idx",
    ),
    (
        "228_channel_media_pending_object_key_index",
        "channel_media_pending_object_storage_key_uidx",
    ),
    (
        "230_channel_media_pending_object_claim_index",
        "idx_channel_media_pending_object_claim",
    ),
    (
        "231_agent_task_queue_terminal_completed_at_index",
        "idx_agent_task_queue_terminal_completed_at",
    ),
    (
        "232_channel_media_pending_object_due_index",
        "idx_channel_media_pending_object_due",
    ),
    (
        "233_agent_task_queue_agent_terminal_latest_index",
        "idx_agent_task_queue_agent_terminal_latest",
    ),
    (
        "238_quick_action_workspace_index",
        "idx_quick_action_workspace_status_usage",
    ),
    (
        "241_comment_parent_lookup_index",
        "idx_comment_workspace_issue_parent",
    ),
    (
        "244_issue_dependency_issue_index",
        "idx_issue_dependency_issue_id",
    ),
    (
        "245_issue_dependency_depends_on_index",
        "idx_issue_dependency_depends_on_issue_id",
    ),
    ("246_inbox_item_issue_index", "idx_inbox_item_issue_id"),
    ("247_comment_parent_index", "idx_comment_parent_id"),
    (
        "248_agent_task_trigger_comment_index",
        "idx_agent_task_queue_trigger_comment_id",
    ),
    (
        "255_agent_task_queue_chat_pending_deferred_v3",
        "idx_agent_task_queue_chat_pending_v3",
    ),
    (
        "257_agent_task_queue_channel_media_pending_unique_v2",
        "idx_one_pending_task_per_issue_agent_v2",
    ),
    (
        "261_agent_task_queue_terminal_completed_at_v2",
        "idx_agent_task_queue_terminal_completed_at_v2",
    ),
    ("266_issue_view_owner_index", "idx_issue_view_owner"),
    ("267_issue_view_shared_index", "idx_issue_view_shared"),
    (
        "273_agent_task_queue_runtime_id_index",
        "idx_agent_task_queue_runtime_id",
    ),
    (
        "274_task_token_workspace_id_index",
        "idx_task_token_workspace_id",
    ),
    ("275_task_token_agent_id_index", "idx_task_token_agent_id"),
    (
        "276_chat_draft_restore_task_id_index",
        "idx_chat_draft_restore_task_id",
    ),
    (
        "277_autopilot_run_task_id_index",
        "idx_autopilot_run_task_id",
    ),
    (
        "278_agent_task_queue_agent_id_keyset_index",
        "idx_agent_task_queue_agent_id_keyset",
    ),
    (
        "279_agent_task_queue_issue_id_keyset_index",
        "idx_agent_task_queue_issue_id_keyset",
    ),
    (
        "281_agent_workspace_id_keyset_index",
        "idx_agent_workspace_id_keyset",
    ),
    (
        "282_issue_workspace_id_keyset_index",
        "idx_issue_workspace_id_keyset",
    ),
    (
        "283_agent_runtime_workspace_id_keyset_index",
        "idx_agent_runtime_workspace_id_keyset",
    ),
    ("286_plugin_identity_key_index", "idx_plugin_identity_key"),
    (
        "287_plugin_release_version_index",
        "idx_plugin_release_version",
    ),
    (
        "288_plugin_installation_workspace_plugin_index",
        "idx_plugin_installation_workspace_plugin_active",
    ),
    (
        "289_plugin_contribution_key_index",
        "idx_plugin_contribution_release_key",
    ),
    (
        "290_plugin_contribution_ordinal_index",
        "idx_plugin_contribution_release_ordinal",
    ),
    (
        "291_plugin_grant_revision_index",
        "idx_plugin_grant_revision",
    ),
    (
        "292_plugin_binding_revision_index",
        "idx_plugin_binding_revision",
    ),
    (
        "293_plugin_installation_workspace_index",
        "idx_plugin_installation_workspace",
    ),
    (
        "295_plugin_artifact_file_index",
        "idx_plugin_artifact_file_release_path",
    ),
    (
        "296_plugin_snapshot_revision_index",
        "idx_plugin_snapshot_workspace_revision",
    ),
    (
        "297_plugin_execution_task_index",
        "idx_plugin_execution_manifest_task",
    ),
    (
        "298_plugin_health_index",
        "idx_plugin_health_installation_observed",
    ),
    (
        "299_agent_task_plugin_manifest_index",
        "idx_agent_task_plugin_execution_manifest",
    ),
    (
        "305_dingtalk_group_route_installation_conversation_unique",
        "idx_dingtalk_group_route_installation_conversation",
    ),
    (
        "306_dingtalk_group_route_workspace_index",
        "idx_dingtalk_group_route_workspace",
    ),
    (
        "307_dingtalk_group_route_id_unique",
        "idx_dingtalk_group_route_id_unique",
    ),
    ("309_agent_runtime_id_index", "idx_agent_runtime_id"),
    (
        "311_plugin_identity_scoped_key_index",
        "idx_plugin_identity_scoped_key",
    ),
    (
        "316_workspace_mcp_server_name_unique",
        "idx_workspace_mcp_server_workspace_name",
    ),
    (
        "317_agent_mcp_server_server_index",
        "idx_agent_mcp_server_server",
    ),
    (
        "320_plugin_installation_config_revision_index",
        "idx_plugin_installation_config_contribution_revision",
    ),
    (
        "321_plugin_installation_config_workspace_index",
        "idx_plugin_installation_config_workspace",
    ),
    (
        "322_plugin_remote_mcp_secret_revision_index",
        "idx_plugin_remote_mcp_secret_revision",
    ),
    (
        "323_plugin_remote_mcp_secret_workspace_index",
        "idx_plugin_remote_mcp_secret_workspace",
    ),
    (
        "324_plugin_remote_mcp_one_active_secret_index",
        "idx_plugin_remote_mcp_one_active_secret",
    ),
    (
        "326_plugin_remote_mcp_oauth_state_expiry_index",
        "plugin_remote_mcp_oauth_state_expiry_idx",
    ),
    (
        "328_workspace_share_link_id_uidx",
        "workspace_share_link_pkey_uidx",
    ),
    (
        "330_workspace_share_link_active_ws_uidx",
        "workspace_share_link_active_ws_uidx",
    ),
    (
        "331_workspace_share_link_code_uidx",
        "workspace_share_link_code_uidx",
    ),
    ("333_issue_status_pkey_index", "issue_status_pkey_uidx"),
    (
        "335_issue_status_workspace_key_index",
        "idx_issue_status_workspace_key",
    ),
    (
        "336_issue_status_workspace_name_index",
        "idx_issue_status_workspace_name_active",
    ),
    (
        "343_comment_delegated_failure_pending_index",
        "idx_comment_delegated_failure_pending",
    ),
    (
        "345_plugin_installation_workspace_key_index",
        "idx_plugin_installation_workspace_key",
    ),
    (
        "346_plugin_storage_scope_key_index",
        "idx_plugin_storage_scope_key",
    ),
    (
        "347_plugin_secret_installation_key_index",
        "idx_plugin_secret_installation_key",
    ),
    (
        "349_agent_task_queue_chat_terminal_resume_index",
        "idx_agent_task_queue_chat_terminal_resume",
    ),
    (
        "350_agent_task_queue_chat_retired_session_index",
        "idx_agent_task_queue_chat_retired_session",
    ),
    (
        "353_autopilot_quota_period_scope_index",
        "uq_autopilot_quota_period_scope",
    ),
    (
        "354_autopilot_quota_reservation_id_index",
        "autopilot_quota_reservation_pkey_uidx",
    ),
    (
        "355_autopilot_quota_reservation_key_index",
        "uq_autopilot_quota_reservation_key",
    ),
    (
        "356_autopilot_run_quota_reservation_index",
        "uq_autopilot_run_quota_reservation",
    ),
    (
        "357_webhook_delivery_replay_idempotency_index",
        "uq_webhook_delivery_replay_idempotency",
    ),
    (
        "358_autopilot_quota_reservation_state_index",
        "idx_autopilot_quota_reservation_state",
    ),
    (
        "361_issue_last_activity_index",
        "idx_issue_workspace_last_activity",
    ),
    (
        "363_plugin_invocation_installation_index",
        "idx_plugin_invocation_installation_created",
    ),
    (
        "364_plugin_invocation_created_at_index",
        "idx_plugin_invocation_created_at",
    ),
    (
        "384_agent_task_queue_side_chat_pending_unique_v3",
        "idx_one_pending_task_per_issue_agent_v3",
    ),
    (
        "387_workspace_channel_id_index",
        "workspace_channel_id_uidx",
    ),
    (
        "389_workspace_channel_slug_index",
        "workspace_channel_workspace_slug_uidx",
    ),
    (
        "391_workspace_channel_message_id_index",
        "workspace_channel_message_id_uidx",
    ),
    (
        "393_workspace_channel_message_channel_index",
        "workspace_channel_message_channel_created_idx",
    ),
    (
        "395_team_no_action_activity_index",
        "idx_activity_log_team_no_action_task",
    ),
    (
        "402_agent_coordination_event_key_index",
        "idx_agent_coordination_outbox_event_key",
    ),
    (
        "403_agent_coordination_assignment_key_index",
        "idx_agent_coordination_assignment_event_role",
    ),
    (
        "404_agent_coordination_pending_index",
        "idx_agent_coordination_outbox_pending",
    ),
    (
        "405_agent_coordination_outbox_id_index",
        "agent_coordination_outbox_pkey_uidx",
    ),
    (
        "406_agent_coordination_assignment_id_index",
        "agent_coordination_assignment_pkey_uidx",
    ),
    (
        "410_agent_task_queue_execution_lane_active_unique",
        "idx_agent_task_queue_execution_lane_active_unique",
    ),
    (
        "412_authorization_grant_id_index",
        "authorization_grant_id_idx",
    ),
    (
        "413_authorization_grant_lookup_index",
        "authorization_grant_lookup_idx",
    ),
    (
        "414_authorization_audit_id_index",
        "authorization_audit_event_id_idx",
    ),
    (
        "415_authorization_audit_lookup_index",
        "authorization_audit_event_lookup_idx",
    ),
    (
        "416_task_capability_parent_index",
        "task_token_parent_token_id_idx",
    ),
    (
        "417_task_capability_claim_fence_index",
        "task_token_claim_fence_idx",
    ),
    (
        "419_dependency_graph_plan_id_index",
        "uq_dependency_graph_plan_id",
    ),
    (
        "420_dependency_graph_node_id_index",
        "uq_dependency_graph_node_id",
    ),
    (
        "421_dependency_graph_edge_id_index",
        "uq_dependency_graph_edge_id",
    ),
    (
        "422_dependency_graph_idempotency_index",
        "uq_dependency_graph_plan_idempotency",
    ),
    (
        "423_dependency_graph_active_parent_index",
        "uq_dependency_graph_plan_active_parent",
    ),
    (
        "424_dependency_graph_node_temp_index",
        "uq_dependency_graph_node_plan_temp",
    ),
    (
        "425_dependency_graph_edge_direction_index",
        "uq_dependency_graph_edge_plan_direction",
    ),
    (
        "426_dependency_graph_edge_from_index",
        "idx_dependency_graph_edge_plan_from",
    ),
    (
        "427_dependency_graph_edge_to_index",
        "idx_dependency_graph_edge_plan_to",
    ),
    ("431_work_product_id_index", "work_product_id_uidx"),
    (
        "433_work_product_external_identity_index",
        "work_product_external_identity_uidx",
    ),
    (
        "434_work_product_provider_record_index",
        "work_product_provider_record_idx",
    ),
    (
        "436_work_product_relation_id_index",
        "work_product_relation_id_uidx",
    ),
    (
        "438_work_product_relation_key_index",
        "work_product_relation_active_key_uidx",
    ),
    (
        "439_work_product_relation_issue_index",
        "work_product_relation_issue_idx",
    ),
    (
        "440_work_product_relation_product_index",
        "work_product_relation_product_idx",
    ),
    (
        "441_work_product_relation_task_index",
        "work_product_relation_task_idx",
    ),
    (
        "443_agent_task_execution_provenance_identity_index",
        "agent_task_execution_provenance_identity_uidx",
    ),
    (
        "445_agent_task_execution_provenance_branch_index",
        "agent_task_execution_provenance_branch_idx",
    ),
    (
        "450_agent_task_execution_provenance_discovery_queue_index",
        "agent_task_execution_provenance_discovery_queue_idx",
    ),
    (
        "452_chat_message_channel_task_index",
        "idx_chat_message_channel_task",
    ),
    (
        "453_patrick_workspace_unique_index",
        "uq_agent_workspace_patrick",
    ),
    (
        "457_issue_workspace_executor_index",
        "idx_issue_workspace_executor",
    ),
    (
        "458_issue_workspace_owner_index",
        "idx_issue_workspace_owner",
    ),
    (
        "462_issue_category_policy_workspace_category_index",
        "uq_workspace_issue_category_policy_workspace_category",
    ),
    (
        "466_slack_oauth_state_hash_index",
        "slack_oauth_state_hash_uidx",
    ),
    ("466_linear_connection_id_index", "uq_linear_connection_id"),
    (
        "467_linear_connection_workspace_index",
        "uq_linear_connection_workspace",
    ),
    (
        "468_linear_connection_identity_index",
        "uq_linear_connection_identity",
    ),
    (
        "469_linear_oauth_state_id_index",
        "uq_linear_oauth_state_id",
    ),
    (
        "470_linear_oauth_state_hash_index",
        "uq_linear_oauth_state_hash",
    ),
    (
        "471_linear_oauth_state_expiry_index",
        "idx_linear_oauth_state_expiry",
    ),
    ("472_linear_sync_inbox_id_index", "uq_linear_sync_inbox_id"),
    (
        "473_linear_sync_inbox_delivery_index",
        "uq_linear_sync_inbox_delivery",
    ),
    (
        "474_linear_sync_inbox_pending_index",
        "idx_linear_sync_inbox_pending",
    ),
    (
        "476_linear_project_binding_id_index",
        "uq_linear_project_binding_id",
    ),
    (
        "477_linear_project_binding_remote_index",
        "uq_linear_project_binding_remote",
    ),
    (
        "478_linear_project_binding_local_index",
        "uq_linear_project_binding_local",
    ),
    (
        "479_linear_project_binding_status_index",
        "idx_linear_project_binding_status",
    ),
];

pub(crate) const CONCURRENT_INDEX_CLEANUPS_DOWN: &[(&str, &str)] = &[
    (
        "144_drop_agent_task_queue_chat_pending_v1",
        "idx_agent_task_queue_chat_pending",
    ),
    (
        "171_drop_legacy_label_namespace_index",
        "issue_label_workspace_name_lower_idx",
    ),
    (
        "256_drop_agent_task_queue_chat_pending_v2",
        "idx_agent_task_queue_chat_pending_v2",
    ),
    (
        "258_drop_pending_issue_agent_v1",
        "idx_one_pending_task_per_issue_agent",
    ),
    (
        "262_drop_agent_task_queue_terminal_completed_at_v1",
        "idx_agent_task_queue_terminal_completed_at",
    ),
    (
        "300_drop_redundant_issue_workspace_number_index",
        "idx_issue_workspace_number",
    ),
    (
        "301_drop_redundant_sys_cron_job_plan_index",
        "idx_sys_cron_exec_job_plan",
    ),
    (
        "302_drop_redundant_channel_chat_session_binding_index",
        "idx_channel_chat_session_binding_session",
    ),
    (
        "385_drop_pending_issue_agent_v2",
        "idx_one_pending_task_per_issue_agent_v2",
    ),
    (
        "303_drop_redundant_lark_chat_session_binding_index",
        "idx_lark_chat_session_binding_session",
    ),
    (
        "312_drop_global_plugin_identity_key_index",
        "idx_plugin_identity_key",
    ),
    (
        "371_comment_content_search_index_strategy",
        "idx_comment_content_trgm",
    ),
    (
        "375_drop_issue_last_activity_index",
        "idx_issue_workspace_last_activity",
    ),
    (
        "410_agent_task_queue_execution_lane_active_unique",
        "idx_agent_task_queue_execution_lane_active_unique",
    ),
    (
        "419_dependency_graph_plan_id_index",
        "uq_dependency_graph_plan_id",
    ),
    (
        "420_dependency_graph_node_id_index",
        "uq_dependency_graph_node_id",
    ),
    (
        "421_dependency_graph_edge_id_index",
        "uq_dependency_graph_edge_id",
    ),
    (
        "422_dependency_graph_idempotency_index",
        "uq_dependency_graph_plan_idempotency",
    ),
    (
        "423_dependency_graph_active_parent_index",
        "uq_dependency_graph_plan_active_parent",
    ),
    (
        "424_dependency_graph_node_temp_index",
        "uq_dependency_graph_node_plan_temp",
    ),
    (
        "425_dependency_graph_edge_direction_index",
        "uq_dependency_graph_edge_plan_direction",
    ),
    (
        "426_dependency_graph_edge_from_index",
        "idx_dependency_graph_edge_plan_from",
    ),
    (
        "427_dependency_graph_edge_to_index",
        "idx_dependency_graph_edge_plan_to",
    ),
    ("431_work_product_id_index", "work_product_id_uidx"),
    (
        "433_work_product_external_identity_index",
        "work_product_external_identity_uidx",
    ),
    (
        "434_work_product_provider_record_index",
        "work_product_provider_record_idx",
    ),
    (
        "436_work_product_relation_id_index",
        "work_product_relation_id_uidx",
    ),
    (
        "438_work_product_relation_key_index",
        "work_product_relation_active_key_uidx",
    ),
    (
        "439_work_product_relation_issue_index",
        "work_product_relation_issue_idx",
    ),
    (
        "440_work_product_relation_product_index",
        "work_product_relation_product_idx",
    ),
    (
        "441_work_product_relation_task_index",
        "work_product_relation_task_idx",
    ),
    (
        "443_agent_task_execution_provenance_identity_index",
        "agent_task_execution_provenance_identity_uidx",
    ),
    (
        "445_agent_task_execution_provenance_branch_index",
        "agent_task_execution_provenance_branch_idx",
    ),
    (
        "450_agent_task_execution_provenance_discovery_queue_index",
        "agent_task_execution_provenance_discovery_queue_idx",
    ),
    (
        "453_patrick_workspace_unique_index",
        "uq_agent_workspace_patrick",
    ),
    ("455_drop_issue_assignee_index", "idx_issue_assignee"),
    (
        "456_drop_issue_workspace_assignee_index",
        "idx_issue_workspace_assignee",
    ),
    (
        "457_issue_workspace_executor_index",
        "idx_issue_workspace_executor",
    ),
    (
        "458_issue_workspace_owner_index",
        "idx_issue_workspace_owner",
    ),
    (
        "462_issue_category_policy_workspace_category_index",
        "uq_workspace_issue_category_policy_workspace_category",
    ),
    ("466_linear_connection_id_index", "uq_linear_connection_id"),
    (
        "467_linear_connection_workspace_index",
        "uq_linear_connection_workspace",
    ),
    (
        "468_linear_connection_identity_index",
        "uq_linear_connection_identity",
    ),
    (
        "469_linear_oauth_state_id_index",
        "uq_linear_oauth_state_id",
    ),
    (
        "470_linear_oauth_state_hash_index",
        "uq_linear_oauth_state_hash",
    ),
    (
        "471_linear_oauth_state_expiry_index",
        "idx_linear_oauth_state_expiry",
    ),
    ("472_linear_sync_inbox_id_index", "uq_linear_sync_inbox_id"),
    (
        "473_linear_sync_inbox_delivery_index",
        "uq_linear_sync_inbox_delivery",
    ),
    (
        "474_linear_sync_inbox_pending_index",
        "idx_linear_sync_inbox_pending",
    ),
    (
        "476_linear_project_binding_id_index",
        "uq_linear_project_binding_id",
    ),
    (
        "477_linear_project_binding_remote_index",
        "uq_linear_project_binding_remote",
    ),
    (
        "478_linear_project_binding_local_index",
        "uq_linear_project_binding_local",
    ),
    (
        "479_linear_project_binding_status_index",
        "idx_linear_project_binding_status",
    ),
];
