import {act,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,expect,it,vi} from 'vitest';
import type {DependencyGraphResponse} from '@orvilo/core/types';
import {TaskGraphPage} from './task-graph-page';
import locale from '../locales/zh-Hans/task-graph.json';

const state=vi.hoisted(()=>({graphs:[] as DependencyGraphResponse[],events:new Map<string,()=>void>()}));
vi.mock('@orvilo/core/dependency-graphs',()=>({dependencyGraphKeys:{all:(ws:string)=>['graph',ws]},dependencyGraphsOptions:(ws:string)=>({queryKey:['graph',ws],queryFn:async()=>state.graphs})}));
vi.mock('@orvilo/core/hooks',()=>({useWorkspaceId:()=> 'ws'}));
vi.mock('@orvilo/core/paths',()=>({useWorkspacePaths:()=>({issues:()=>'/acme/issues',issueDetail:(id:string)=>'/acme/issues/'+id})}));
vi.mock('@orvilo/core/workspace/hooks',()=>({useActorName:()=>({getActorName:()=> 'Patrick'})}));
vi.mock('@orvilo/core/realtime',()=>({useWSEvent:(event:string,callback:()=>void)=>state.events.set(event,callback),useWSReconnect:()=>{}}));
vi.mock('../issues/utils/status-label',()=>({useStatusLabel:()=>((status:string)=>({in_progress:'进行中',in_review:'审核中',todo:'待办'}[status]??status))}));
vi.mock('../i18n',()=>({useT:()=>({t:(select:(v:typeof locale)=>string,params:Record<string,string|number>={})=>select(locale).replace(/{{(\w+)}}/g,(_,key)=>String(params[key]??key))})}));
vi.mock('../layout',()=>({CollectionPageHeader:({title,description,actions}:any)=><header><h1>{title}</h1><p>{description}</p>{actions}</header>,CollectionPageHeaderAction:({label,onClick}:any)=><button onClick={onClick}>{label}</button>,CollectionPageState:({title,description,actions}:any)=><div>{title}{description}{actions}</div>}));
vi.mock('../layout/shell-header',()=>({ShellHeaderActions:({children}: {children: React.ReactNode})=><header>{children}</header>}));
vi.mock('../navigation',()=>({AppLink:({href,children,className}:any)=><a href={href} className={className}>{children}</a>}));
vi.mock('../issues/components/board-card',()=>({BoardCardContent:({issue}:any)=><div><span>{issue.identifier}</span><span>{issue.title}</span></div>}));
vi.mock('@orvilo/core/issue-views/use-active-view',()=>({useActiveIssueView:()=>({activeView:null})}));
afterEach(()=>state.events.clear());
it('renders only the graph; issue updates refresh status/title and preserve details interaction',async()=>{
 const graph={plan:{id:'p',goal:'不应显示的计划说明'},parent:{title:'不应显示的计划标题'},nodes:[{id:'n',temp_id:'a',issue_id:'i',title:'旧计划标题',wave:0,status:'in_progress',status_category:'in_progress',acceptance_criteria:[],issue:{id:'i',identifier:'ACME-4',title:'当前任务标题',status:'in_progress',status_category:'in_progress',executor_type:'agent',executor_id:'a'}}],edges:[]} as unknown as DependencyGraphResponse;
 state.graphs=[graph];const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
 render(<QueryClientProvider client={client}><TaskGraphPage/></QueryClientProvider>);
 expect(await screen.findByText('当前任务标题')).toBeInTheDocument();
 expect(screen.getByRole('link',{name:'返回看板'})).toHaveAttribute('href','/acme/issues');
 expect(screen.queryByRole('combobox')).not.toBeInTheDocument();
 expect(screen.queryByRole('button',{name:'列表'})).not.toBeInTheDocument();
 expect(screen.queryByText('不应显示的计划说明')).not.toBeInTheDocument();
 expect(screen.queryByText('不应显示的计划标题')).not.toBeInTheDocument();
 expect(screen.queryByText(/个任务.*个/)).not.toBeInTheDocument();
 expect(screen.queryByRole('complementary')).not.toBeInTheDocument();
 state.graphs=[{...graph,nodes:[{...graph.nodes[0]!,issue:{...graph.nodes[0]!.issue!,title:'更新后的任务标题',status:'in_review',status_category:'in_review'}}]}];
 await act(async()=>state.events.get('issue:updated')?.());
 await waitFor(()=>expect(screen.getByText('更新后的任务标题')).toBeInTheDocument());
 expect(screen.queryByText('当前任务标题')).not.toBeInTheDocument();
 expect(screen.getByRole('button',{name:'ACME-4：更新后的任务标题，审核中。'})).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'ACME-4：更新后的任务标题，审核中。'}));
 expect(await screen.findByRole('complementary')).toHaveTextContent('Patrick');
 fireEvent.click(screen.getByRole('button',{name:'关闭任务详情'}));
 expect(screen.queryByRole('complementary')).not.toBeInTheDocument();
 client.clear();
});
