#!/usr/bin/env bash
set -euo pipefail

# Operator-only helper for the server-managed messaging deployment. The app
# remains read-only in server_configured mode; this script is the copyable
# deployment path for an administrator and never prints secret values.

ROOT_DIR="${PATCHBAY_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
MANIFEST="${PATCHBAY_MESSAGING_MANIFEST:-${ROOT_DIR}/deploy/messaging/manifest.yaml}"
SLACK_MANIFEST="${PATCHBAY_SLACK_MANIFEST:-${ROOT_DIR}/deploy/messaging/slack-app-manifest.yaml}"
CHECK_SCRIPT="${ROOT_DIR}/scripts/messaging-self-host-check.sh"

usage() {
  cat <<'EOF'
Usage:
  scripts/messaging-self-host-setup.sh init --app-url URL --api-url URL [--env-file PATH]
  scripts/messaging-self-host-setup.sh check
  scripts/messaging-self-host-setup.sh slack-manifest

init writes a mode/public-origin and bootstrap template for the server
deployment. It does not print or generate provider credentials. Add the
workspace/installer ids and provider values to the server secret store, then
run check before starting the gateway. With PATCHBAY_MESSAGING_BOOTSTRAP=true,
the server encrypts those values and materializes installation rows at boot.
EOF
}

fail() {
  echo "messaging self-host setup: $*" >&2
  exit 1
}

require_https_public_origin() {
  local name="$1" value="$2"
  [[ "$value" == https://* ]] || fail "$name must be an HTTPS URL"
  local host="${value#https://}"
  host="${host%%/*}"
  if [[ "$host" == \[*\]* ]]; then
    host="${host#\[}"
    host="${host%%\]*}"
    local ipv6_lower
    ipv6_lower="$(printf '%s' "$host" | tr '[:upper:]' '[:lower:]')"
    case "$ipv6_lower" in
      ""|::|::1|fc*|fd*|fe8*|fe9*|fea*|feb*)
        fail "$name must be reachable from phones and providers, not a private or loopback IPv6 host"
        ;;
    esac
    return
  fi
  host="${host%%:*}"
  local host_lower
  host_lower="$(printf '%s' "$host" | tr '[:upper:]' '[:lower:]')"
  case "$host_lower" in
    localhost|*.local|0.*|127.*|10.*|100.64.*|169.254.*|192.0.0.*|192.168.*|198.18.*|198.19.*|172.16.*|172.17.*|172.18.*|172.19.*|172.2[0-9].*|172.3[0-1].*)
      fail "$name must be reachable from phones and providers, not a private or loopback host"
      ;;
  esac
}

init_env() {
  local app_url="" api_url="" env_file=".env.messaging" force="false"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --app-url) [[ $# -ge 2 ]] || fail "--app-url needs a value"; app_url="$2"; shift 2 ;;
      --api-url) [[ $# -ge 2 ]] || fail "--api-url needs a value"; api_url="$2"; shift 2 ;;
      --env-file) [[ $# -ge 2 ]] || fail "--env-file needs a path"; env_file="$2"; shift 2 ;;
      --force) force="true"; shift ;;
      -h|--help) usage; exit 0 ;;
      *) fail "unknown init option: $1" ;;
    esac
  done

  [[ -n "$app_url" ]] || fail "--app-url is required"
  [[ -n "$api_url" ]] || fail "--api-url is required"
  require_https_public_origin PATCHBAY_APP_URL "$app_url"
  require_https_public_origin PATCHBAY_PUBLIC_URL "$api_url"
  [[ -f "$MANIFEST" ]] || fail "manifest not found: $MANIFEST"
  [[ -f "$SLACK_MANIFEST" ]] || fail "Slack app manifest not found: $SLACK_MANIFEST"

  if [[ -e "$env_file" && "$force" != "true" ]]; then
    fail "$env_file already exists; choose another path or pass --force"
  fi

  umask 077
  mkdir -p "$(dirname "$env_file")"
  cat >"$env_file" <<EOF
# Generated by scripts/messaging-self-host-setup.sh. Keep mode and public origins.
PATCHBAY_MESSAGING_MODE=server_configured
PATCHBAY_APP_URL=$app_url
PATCHBAY_PUBLIC_URL=$api_url

# Server-owned installation scope. Required when bootstrap is enabled.
PATCHBAY_MESSAGING_BOOTSTRAP=false
PATCHBAY_MESSAGING_WORKSPACE_ID=
PATCHBAY_MESSAGING_INSTALLER_USER_ID=
PATCHBAY_MESSAGING_AGENT_ID=

# Generate each encryption key with: openssl rand -base64 32
PATCHBAY_SLACK_SECRET_KEY=
PATCHBAY_TELEGRAM_SECRET_KEY=
PATCHBAY_LARK_SECRET_KEY=
PATCHBAY_DINGTALK_SECRET_KEY=
PATCHBAY_WECOM_SECRET_KEY=
PATCHBAY_WEIXIN_SECRET_KEY=

# Provider values are read only by the server bootstrap path. Keep this file
# in the deployment secret store (mode 0600); never paste them into the app.
SLACK_APP_TOKEN=
SLACK_BOT_TOKEN=
SLACK_APP_ID=
SLACK_TEAM_ID=
SLACK_BOT_USER_ID=
TELEGRAM_BOT_TOKEN=
TELEGRAM_BOT_USERNAME=
LARK_APP_ID=
LARK_APP_SECRET=
LARK_TENANT_KEY=
LARK_BOT_OPEN_ID=
LARK_BOT_UNION_ID=
LARK_REGION=feishu
DINGTALK_CLIENT_ID=
DINGTALK_CLIENT_SECRET=
DINGTALK_ROBOT_CODE=
WECOM_BOT_ID=
WECOM_SECRET=
WECOM_BOT_NAME=

# Provider credentials belong in the deployment secret manager. Do not commit
# them or put them in the Cordy app. Slack uses the tokens created from the
# checked-in Socket Mode manifest; the other providers use their documented
# server-side transport credentials.
EOF
  echo "messaging self-host setup: wrote $env_file (mode and public origins only)"
  echo "next: store provider credentials securely, source $env_file, then run:"
  echo "  PATCHBAY_MESSAGING_MANIFEST=$MANIFEST scripts/messaging-self-host-setup.sh check"
}

check() {
  [[ -x "$CHECK_SCRIPT" ]] || fail "check script is not executable: $CHECK_SCRIPT"
  exec "$CHECK_SCRIPT"
}

slack_manifest() {
  [[ -f "$SLACK_MANIFEST" ]] || fail "Slack app manifest not found: $SLACK_MANIFEST"
  cat "$SLACK_MANIFEST"
}

[[ $# -gt 0 ]] || { usage; exit 2; }
command="$1"
shift
case "$command" in
  init) init_env "$@" ;;
  check) [[ $# -eq 0 ]] || fail "check does not accept options"; check ;;
  slack-manifest) [[ $# -eq 0 ]] || fail "slack-manifest does not accept options"; slack_manifest ;;
  -h|--help) usage ;;
  *) fail "unknown command: $command" ;;
esac
