name = "aspectlylabs-proxy"
main = "src/index.js"
compatibility_date = "2026-08-30"
account_id = "d8f6630c7869111a5139bc5ed4d24ace"

[[routes]]
pattern = "accounts.aspectlylabs.com"
custom_domain = true

[vars]
ORIGIN = "https://accounts-origin.aspectlylabs.com"

[[ratelimits]]
name = "DESKTOP_ATTEMPT_RATE_LIMITER"
namespace_id = "13410502821"
  [ratelimits.simple]
  limit = 20
  period = 60

[[ratelimits]]
name = "DESKTOP_COMPLETE_RATE_LIMITER"
namespace_id = "13410502822"
  [ratelimits.simple]
  limit = 10
  period = 60
