//! Port of execenv/codex_shell_env.go.
//!
//! Symbol map:
//! - shellEnvironmentPolicyKey → SHELL_ENVIRONMENT_POLICY_KEY
//! - cordyShellEnvBegin/EndMarker → CORDY_SHELL_ENV_BEGIN_MARKER / CORDY_SHELL_ENV_END_MARKER
//! - shellEnvBlockRe           → shell_env_block_re
//! - codexShellEnvironmentPolicy → folded into render_cordy_shell_env_block's
//!   manual TOML rendering (see deviations)
//! - CodexShellEnvAllowlist    → codex_shell_env_allowlist
//! - codexDefaultExcludesEnvKey → codex_default_excludes_env_key
//! - renderCordyShellEnvBlock  → render_cordy_shell_env_block
//! - stripUserShellEnvPolicy   → strip_user_shell_env_policy
//! - tomlNodeKeys / isCodexShellEnvPolicyPath / tomlTableHeaderLineRange /
//!   removeTOMLByteRanges → folded into the line-scanner below
//! - EnsureCodexShellEnvPolicyConfig → ensure_codex_shell_env_policy_config
//!
//! Deviations:
//! - slog logger parameter dropped; tracing macros used directly.
//! - Go strips user expressions via go-toml's unstable parser byte ranges.
//!   Rust's toml crate exposes no source positions, so this port scans lines:
//!   a table header or key-value expression whose full key path names the
//!   shell_environment_policy is dropped whole, with brace/bracket balancing
//!   carrying multi-line inline tables and arrays. Comments and every
//!   unrelated expression are preserved byte-for-byte; the result is
//!   re-validated with the stable decoder before any write, so a mis-scan can
//!   never produce invalid TOML on disk.
//! - The rendered block uses basic-string array elements rather than go-toml
//!   v2's literal-quote style; clients parse TOML, so semantic content is
//!   identical.

use anyhow::Context;
use regex::Regex;
use std::collections::HashMap;

/// Codex filters environment variables before running shell tool subprocesses.
/// Its default secret guard drops names containing KEY, SECRET, or TOKEN, so a
/// daemon-spawned Codex process can have CORDY_TOKEN while `cordy issue ...`
/// inside a shell tool does not. The daemon therefore owns the shell policy in
/// each task's isolated Codex home.
const SHELL_ENVIRONMENT_POLICY_KEY: &str = "shell_environment_policy";
const CORDY_SHELL_ENV_BEGIN_MARKER: &str =
    "# BEGIN cordy-managed shell-environment (do not edit; regenerated by daemon)";
const CORDY_SHELL_ENV_END_MARKER: &str = "# END cordy-managed shell-environment";

fn shell_env_block_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(&format!(
            r"(?ms)^{}.*?^{}\n*",
            regex::escape(CORDY_SHELL_ENV_BEGIN_MARKER),
            regex::escape(CORDY_SHELL_ENV_END_MARKER)
        ))
        .expect("static regex")
    })
}

/// Returns exact (not glob) environment names for the managed shell policy.
///
/// Inherited process variables keep Codex's documented default filtering for
/// names containing KEY, SECRET, or TOKEN. Credential-looking explicit values
/// are included only when their names also appear in authorized_explicit,
/// which daemon.go derives solely from the current agent's blocklist-checked
/// custom_env. Inherited CORDY_* variables are always dropped because they
/// belong to the daemon process, not necessarily to this task. Explicit
/// CORDY_* values are safe to include because daemon.go blocklists that
/// namespace from agent custom_env and constructs those values from the
/// current task.
pub fn codex_shell_env_allowlist(
    inherited: &[String],
    explicit: &HashMap<String, String>,
    authorized_explicit: &[String],
) -> Vec<String> {
    let mut authorized: HashMap<String, ()> = HashMap::with_capacity(authorized_explicit.len());
    for key in authorized_explicit {
        if !key.is_empty() {
            authorized.insert(key.to_uppercase(), ());
        }
    }

    // Codex's glob matching is case-insensitive. De-duplicate on the same
    // basis so Windows Path/PATH aliases cannot create ambiguous policy
    // entries.
    let mut allowed: HashMap<String, String> =
        HashMap::with_capacity(inherited.len() + explicit.len());
    let mut add = |key: &str, is_explicit: bool| {
        if key.is_empty() {
            return;
        }
        let upper = key.to_uppercase();
        if upper.starts_with("CORDY_") {
            if !is_explicit {
                return;
            }
        } else if codex_default_excludes_env_key(&upper) {
            if !is_explicit {
                return;
            }
            if !authorized.contains_key(&upper) {
                return;
            }
        }
        allowed.insert(upper, key.to_string());
    };

    for entry in inherited {
        let Some((key, _)) = entry.split_once('=') else {
            continue;
        };
        add(key, false);
    }
    for key in explicit.keys() {
        add(key, true);
    }

    let mut keys: Vec<String> = allowed.into_values().collect();
    keys.sort_by_key(|a| a.to_uppercase());
    keys
}

fn codex_default_excludes_env_key(upper_key: &str) -> bool {
    upper_key.contains("KEY") || upper_key.contains("SECRET") || upper_key.contains("TOKEN")
}

/// Renders the managed shell_environment_policy block with one validated
/// daemon-managed policy: inherit everything, ignore Codex's default secret
/// excludes, and include exactly the allowlisted names.
fn render_cordy_shell_env_block(include_only: &[String]) -> String {
    let items: Vec<String> = include_only.iter().map(|s| toml_basic_string(s)).collect();
    let mut b = String::new();
    b.push_str(CORDY_SHELL_ENV_BEGIN_MARKER);
    b.push('\n');
    b.push('[');
    b.push_str(SHELL_ENVIRONMENT_POLICY_KEY);
    b.push_str("]\n");
    b.push_str("inherit = \"all\"\n");
    b.push_str("ignore_default_excludes = true\n");
    b.push_str(&format!("include_only = [{}]\n", items.join(", ")));
    b.push_str(CORDY_SHELL_ENV_END_MARKER);
    b.push('\n');
    b
}

/// Basic TOML string with escapes, matching what a TOML encoder emits for
/// arbitrary env-var names.
fn toml_basic_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Reports whether a full dotted key path names the shell_environment_policy —
/// at the root, or as a profile overlay (`profiles.<name>.
/// shell_environment_policy`).
fn is_codex_shell_env_policy_path(keys: &[String]) -> bool {
    if keys.first().map(|k| k == SHELL_ENVIRONMENT_POLICY_KEY).unwrap_or(false) {
        return true;
    }
    keys.len() >= 3 && keys[0] == "profiles" && keys[2] == SHELL_ENVIRONMENT_POLICY_KEY
}

/// Splits a dotted TOML key into segments, honoring quoted segments and
/// stripping their quotes so `"name"` matches bare `name`.
fn split_toml_key(key: &str) -> Vec<String> {
    let mut segs: Vec<String> = Vec::new();
    let mut cur = String::new();
    let mut in_quote: Option<char> = None;
    for c in key.chars() {
        match in_quote {
            Some(q) => {
                if c == q {
                    in_quote = None;
                } else {
                    cur.push(c);
                }
            }
            None => {
                if c == '"' || c == '\'' {
                    in_quote = Some(c);
                } else if c == '.' {
                    segs.push(cur.trim().to_string());
                    cur = String::new();
                } else {
                    cur.push(c);
                }
            }
        }
    }
    segs.push(cur.trim().to_string());
    segs.retain(|s| !s.is_empty());
    segs
}

/// Extracts the key segments of a `key = value` line, or None when the line
/// has no top-level `=` outside quotes/comments.
fn kv_line_key_segments(line: &str) -> Option<Vec<String>> {
    let bytes = line.as_bytes();
    let mut in_quote: Option<char> = None;
    let mut escaped = false;
    for (i, &b) in bytes.iter().enumerate() {
        let c = b as char;
        if let Some(q) = in_quote {
            if escaped {
                escaped = false;
            } else if c == '\\' && q == '"' {
                escaped = true;
            } else if c == q {
                in_quote = None;
            }
            continue;
        }
        match c {
            '"' | '\'' => in_quote = Some(c),
            '#' => return None,
            '=' => {
                let key_part = line[..i].trim();
                if key_part.is_empty() {
                    return None;
                }
                return Some(split_toml_key(key_part));
            }
            _ => {}
        }
    }
    None
}

/// Net bracket/brace balance of a line, ignoring quoted spans and comments.
/// Values >0 mean the expression continues onto following lines.
fn delimiter_balance(line: &str) -> i32 {
    let mut bal = 0i32;
    let mut in_quote: Option<char> = None;
    let mut escaped = false;
    for c in line.chars() {
        if let Some(q) = in_quote {
            if escaped {
                escaped = false;
            } else if c == '\\' && q == '"' {
                escaped = true;
            } else if c == q {
                in_quote = None;
            }
            continue;
        }
        match c {
            '"' | '\'' => in_quote = Some(c),
            '[' | '{' => bal += 1,
            ']' | '}' => bal -= 1,
            '#' => break,
            _ => {}
        }
    }
    bal
}

fn header_line_segments(trimmed: &str) -> Vec<String> {
    let inner = trimmed
        .trim_start_matches('[')
        .split(']')
        .next()
        .unwrap_or("");
    split_toml_key(inner)
}

/// Removes complete TOML expressions that define a shell_environment_policy,
/// including root dotted/inline values, quoted table forms, nested set tables,
/// and profile overlays. It deliberately preserves comments and every
/// unrelated expression byte-for-byte.
///
/// See the module-header deviation note for how this differs from Go's
/// unstable-parser implementation.
fn strip_user_shell_env_policy(content: &str) -> anyhow::Result<String> {
    if content.trim().is_empty() {
        return Ok(content.to_string());
    }

    // Validate with the stable decoder first so a malformed user config is
    // never partially rewritten into a different malformed config.
    let _: toml::Value = content
        .parse()
        .context("parse config.toml before shell environment update")?;

    let mut out: Vec<&str> = Vec::new();
    let mut current_table: Vec<String> = Vec::new();
    let mut dropping_table = false;
    let mut dropping_expr = false;
    let mut expr_balance = 0i32;

    for line in content.split('\n') {
        if dropping_expr {
            expr_balance += delimiter_balance(line);
            if expr_balance > 0 {
                continue;
            }
            dropping_expr = false;
            expr_balance = 0;
            continue;
        }
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            let segs = header_line_segments(trimmed);
            if is_codex_shell_env_policy_path(&segs) {
                dropping_table = true;
                continue;
            }
            dropping_table = false;
            current_table = segs;
            out.push(line);
            continue;
        }
        if dropping_table {
            continue;
        }
        if let Some(mut segs) = kv_line_key_segments(line) {
            let mut full: Vec<String> = current_table.clone();
            full.append(&mut segs);
            if is_codex_shell_env_policy_path(&full) {
                expr_balance = delimiter_balance(line);
                if expr_balance > 0 {
                    dropping_expr = true;
                }
                continue;
            }
        }
        out.push(line);
    }
    Ok(out.join("\n"))
}

/// Replaces every user/profile shell policy in the task-local config with one
/// validated daemon-managed policy. The source config in the user's shared
/// Codex home is never modified.
pub fn ensure_codex_shell_env_policy_config(
    config_path: &str,
    include_only: &[String],
) -> anyhow::Result<()> {
    let data = match std::fs::read_to_string(config_path) {
        Ok(d) => d,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(anyhow::Error::new(e).context("read config.toml")),
    };

    let without_managed = shell_env_block_re().replace_all(&data, "").into_owned();
    let stripped = strip_user_shell_env_policy(&without_managed)?;
    let block = render_cordy_shell_env_block(include_only);

    let base = stripped.trim_end_matches([' ', '\t', '\r', '\n']);
    let updated = if base.is_empty() {
        block
    } else {
        format!("{base}\n\n{block}")
    };
    // Validate the generated config before touching disk.
    let _: toml::Value = updated
        .parse()
        .context("validate generated config.toml shell environment policy")?;

    if updated == data {
        return Ok(());
    }
    std::fs::write(config_path, updated).context("write config.toml")?;
    tracing::debug!(
        config_path = %config_path,
        include_count = include_only.len(),
        "codex shell environment: wrote managed shell_environment_policy"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hm(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
    }

    fn inherited(entries: &[&str]) -> Vec<String> {
        entries.iter().map(|s| s.to_string()).collect()
    }

    // Port of TestCodexShellEnvAllowlist: default excludes honored for
    // inherited vars, explicit values gated on authorization, CORDY_*
    // namespace rules, case-insensitive dedup.
    #[test]
    fn test_codex_shell_env_allowlist() {
        let got = codex_shell_env_allowlist(
            &inherited(&["PATH=/usr/bin", "HOME=/home/u", "API_KEY=secret", "CORDY_TOKEN=t"]),
            &hm(&[("CORDY_TOKEN", "task-token"), ("MY_SECRET", "x"), ("EXTRA", "1")]),
            &["my_secret"],
        );
        assert_eq!(got, vec!["EXTRA", "HOME", "PATH", "MY_SECRET", "CORDY_TOKEN"]);

        // Unauthorized credential-looking explicit value dropped.
        let got = codex_shell_env_allowlist(
            &[],
            &hm(&[("UNAUTHORIZED_KEY", "v")]),
            &[],
        );
        assert!(got.is_empty());

        // Authorized credential-looking explicit value kept.
        let got = codex_shell_env_allowlist(
            &[],
            &hm(&[("authorized_token", "v")]),
            &["Authorized_Token".to_string()],
        );
        assert_eq!(got, vec!["authorized_token"]);

        // Case-insensitive dedup keeps the original casing of whichever entry
        // landed last per uppercase key.
        let got = codex_shell_env_allowlist(
            &inherited(&["Path=/bin"]),
            &hm(&[("PATH", "/usr/bin")]),
            &[],
        );
        assert_eq!(got.len(), 1);

        // Entries without '=' skipped.
        let got = codex_shell_env_allowlist(&inherited(&["garbage"]), &hm(&[]), &[]);
        assert!(got.is_empty());

        // Empty authorized entries ignored.
        let got = codex_shell_env_allowlist(
            &[],
            &hm(&[("KEYX", "v")]),
            &["".to_string()],
        );
        assert!(got.is_empty());
    }

    // Port of TestStripUserShellEnvPolicy: root table, profile overlay table,
    // root dotted assignment, and multi-line inline values all removed while
    // unrelated expressions survive byte-for-byte.
    #[test]
    fn test_strip_user_shell_env_policy_variants() {
        let input = "top = 1\n\
                     [shell_environment_policy]\ninherit = \"core\"\nkeep_flag = true\n\
                     [other]\nvalue = 2\n\
                     [profiles.fast.shell_environment_policy]\ninherit = \"none\"\n\
                     profiles_dotted = 3\n\
                     shell_environment_policy.include_only = [\"A\",\n  \"B\"]\n\
                     after = 4\n";
        let got = strip_user_shell_env_policy(input).unwrap();

        assert!(got.contains("top = 1"));
        assert!(got.contains("[other]"));
        assert!(got.contains("value = 2"));
        assert!(got.contains("profiles_dotted = 3"));
        assert!(got.contains("after = 4"));

        assert!(!got.contains("inherit = "));
        assert!(!got.contains("keep_flag"));
        assert!(!got.contains("include_only"));
        assert!(!got.lines().any(|l| l.trim() == "[shell_environment_policy]"));
        assert!(!got.lines().any(|l| l.trim() == "[profiles.fast.shell_environment_policy]"));

        // Result still parses as valid TOML.
        let parsed: Result<toml::Value, _> = got.parse();
        assert!(parsed.is_ok(), "stripped output invalid: {got}");

        // Malformed input refused up front, never partially rewritten.
        assert!(strip_user_shell_env_policy("this is [ not toml").is_err());

        // Empty input passes through.
        assert_eq!(strip_user_shell_env_policy("").unwrap(), "");
    }

    // Port of TestRenderCordyShellEnvBlock shape: markers wrap a single
    // [shell_environment_policy] table with the fixed three keys.
    #[test]
    fn test_render_cordy_shell_env_block_shape() {
        let block = render_cordy_shell_env_block(&["PATH".to_string(), "HOME".to_string()]);
        assert!(block.starts_with(CORDY_SHELL_ENV_BEGIN_MARKER));
        assert!(block.ends_with("# END cordy-managed shell-environment\n"));
        assert!(block.contains("[shell_environment_policy]\n"));
        assert!(block.contains("inherit = \"all\"\n"));
        assert!(block.contains("ignore_default_excludes = true\n"));
        assert!(block.contains("include_only = [\"PATH\", \"HOME\"]\n"));

        // Empty allowlist renders an empty array.
        let empty = render_cordy_shell_env_block(&[]);
        assert!(empty.contains("include_only = []\n"));

        // Block body parses as TOML.
        let body = block
            .lines()
            .filter(|l| !l.starts_with("# BEGIN") && !l.starts_with("# END"))
            .collect::<Vec<_>>()
            .join("\n");
        let parsed: Result<toml::Value, _> = body.parse();
        assert!(parsed.is_ok());
    }

    // Port of TestEnsureCodexShellEnvPolicyConfigIdempotent: managed block
    // written once, idempotent rewrite, user policies replaced everywhere.
    #[test]
    fn test_ensure_codex_shell_env_policy_config_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("config.toml").to_string_lossy().into_owned();

        ensure_codex_shell_env_policy_config(&path, &["PATH".to_string()]).unwrap();
        let first = std::fs::read_to_string(&path).unwrap();
        assert!(first.starts_with(CORDY_SHELL_ENV_BEGIN_MARKER));
        assert!(first.contains("include_only = [\"PATH\"]"));

        // Idempotent.
        ensure_codex_shell_env_policy_config(&path, &["PATH".to_string()]).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), first);

        // A user policy added after the managed block is stripped and replaced.
        std::fs::write(
            &path,
            format!("{first}[shell_environment_policy]\ninherit = \"none\"\n"),
        )
        .unwrap();
        ensure_codex_shell_env_policy_config(&path, &["PATH".to_string(), "HOME".to_string()])
            .unwrap();
        let healed = std::fs::read_to_string(&path).unwrap();
        assert_eq!(healed.matches(CORDY_SHELL_ENV_BEGIN_MARKER).count(), 1);
        assert!(!healed.contains("inherit = \"none\""));
        assert!(healed.contains("include_only = [\"PATH\", \"HOME\"]"));

        // Profile overlays removed too.
        std::fs::write(
            &path,
            "[profiles.x.shell_environment_policy]\ninherit = \"core\"\n",
        )
        .unwrap();
        ensure_codex_shell_env_policy_config(&path, &[]).unwrap();
        let cleaned = std::fs::read_to_string(&path).unwrap();
        assert!(!cleaned.contains("inherit = \"core\""));
        assert!(cleaned.contains("include_only = []"));
    }

    // Port of TestIsCodexShellEnvPolicyPath: root key and profile overlays
    // match; unrelated paths don't.
    #[test]
    fn test_is_codex_shell_env_policy_path() {
        let mk = |parts: &[&str]| parts.iter().map(|s| s.to_string()).collect::<Vec<_>>();
        assert!(is_codex_shell_env_policy_path(&mk(&["shell_environment_policy"])));
        assert!(is_codex_shell_env_policy_path(&mk(&[
            "shell_environment_policy",
            "include_only"
        ])));
        assert!(is_codex_shell_env_policy_path(&mk(&[
            "profiles",
            "fast",
            "shell_environment_policy"
        ])));
        assert!(!is_codex_shell_env_policy_path(&mk(&["profiles"])));
        assert!(!is_codex_shell_env_policy_path(&mk(&["other"])));
        assert!(!is_codex_shell_env_policy_path(&mk(&[
            "profiles",
            "fast",
            "other"
        ])));
    }
}
