//! Port of execenv/codex_memory.go.
//!
//! Symbol map:
//! - CordyCodexMemoryEnv       → CORDY_CODEX_MEMORY_ENV
//! - cordyMemoryFeatureBegin/EndMarker → CORDY_MEMORY_FEATURE_BEGIN_MARKER / CORDY_MEMORY_FEATURE_END_MARKER
//! - cordyMemoryConfigBegin/EndMarker  → CORDY_MEMORY_CONFIG_BEGIN_MARKER / CORDY_MEMORY_CONFIG_END_MARKER
//! - memoryFeatureBlockRe / memoryConfigBlockRe → memory_feature_block_re / memory_config_block_re
//! - rootMemoriesTableHeaderRe → root_memories_table_header_re
//! - featuresTableMemoriesRe   → features_table_memories_re
//! - rootDottedFeaturesMemoriesRe → root_dotted_features_memories_re
//! - memoriesTableGenerateRe / UseRe → memories_table_generate_re / memories_table_use_re
//! - rootDottedMemoriesGenerateRe / UseRe → root_dotted_memories_generate_re / root_dotted_memories_use_re
//! - codexMemoryEnabled        → codex_memory_enabled
//! - renderCordyMemoryFeatureBlock → render_cordy_memory_feature_block
//! - renderCordyMemoryConfigBlock  → render_cordy_memory_config_block
//! - stripUserMemoryDirectives → strip_user_memory_directives
//! - hasRootMemoriesTable      → has_root_memories_table
//! - injectMemoryFeatureBlockIntoFeaturesTable /
//!   injectMemoryConfigBlockIntoMemoriesTable → the two inject_* wrappers
//! - injectAfterHeader         → inject_after_header
//! - ensureCodexMemoryConfig   → ensure_codex_memory_config
//!
//! Deviations:
//! - slog logger parameter dropped; tracing macros used directly.
//! - rootFeaturesTableHeaderRe lives in codex_multi_agent.rs (same package
//!   var in Go); imported from there.

use anyhow::Context;
use regex::Regex;

use super::codex_multi_agent::{has_root_features_table, root_features_table_header_re};

/// Env var users can set to keep Codex native memory enabled inside
/// daemon-managed tasks. Anything truthy (1, true, yes, on; case-insensitive)
/// keeps the feature on; everything else (including unset) disables it.
pub const CORDY_CODEX_MEMORY_ENV: &str = "CORDY_CODEX_MEMORY";

const CORDY_MEMORY_FEATURE_BEGIN_MARKER: &str =
    "# BEGIN cordy-managed memory-feature (do not edit; regenerated by daemon)";
const CORDY_MEMORY_FEATURE_END_MARKER: &str = "# END cordy-managed memory-feature";
const CORDY_MEMORY_CONFIG_BEGIN_MARKER: &str =
    "# BEGIN cordy-managed memory-config (do not edit; regenerated by daemon)";
const CORDY_MEMORY_CONFIG_END_MARKER: &str = "# END cordy-managed memory-config";

/// `\n*` rather than `\n?` so reruns don't accumulate blank lines when these
/// blocks coexist with the sandbox / multi-agent blocks.
fn memory_feature_block_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(&format!(
            r"(?ms)^{}.*?^{}\n*",
            regex::escape(CORDY_MEMORY_FEATURE_BEGIN_MARKER),
            regex::escape(CORDY_MEMORY_FEATURE_END_MARKER)
        ))
        .expect("static regex")
    })
}

fn memory_config_block_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(&format!(
            r"(?ms)^{}.*?^{}\n*",
            regex::escape(CORDY_MEMORY_CONFIG_BEGIN_MARKER),
            regex::escape(CORDY_MEMORY_CONFIG_END_MARKER)
        ))
        .expect("static regex")
    })
}

/// Matches a top-level `[memories]` table header.
fn root_memories_table_header_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*\[\s*memories\s*\]\s*(?:#.*)?$").expect("static regex"))
}

/// Matches `memories = ...` inside a `[features]` table.
fn features_table_memories_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*memories\s*=").expect("static regex"))
}

/// Matches `features.memories = ...` at the TOML root.
fn root_dotted_features_memories_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*features\s*\.\s*memories\s*=").expect("static regex"))
}

/// Matches `generate_memories = ...` / `use_memories = ...` inside a
/// `[memories]` table.
fn memories_table_generate_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*generate_memories\s*=").expect("static regex"))
}

fn memories_table_use_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*use_memories\s*=").expect("static regex"))
}

/// Matches `memories.generate_memories = ...` / `memories.use_memories = ...`
/// at the TOML root.
fn root_dotted_memories_generate_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(r"^\s*memories\s*\.\s*generate_memories\s*=").expect("static regex")
    })
}

fn root_dotted_memories_use_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*memories\s*\.\s*use_memories\s*=").expect("static regex"))
}

/// Reports whether the user opted into keeping Codex native memory on for
/// daemon-managed tasks.
fn codex_memory_enabled() -> bool {
    let raw = std::env::var(CORDY_CODEX_MEMORY_ENV)
        .unwrap_or_default()
        .trim()
        .to_lowercase();
    matches!(raw.as_str(), "1" | "true" | "yes" | "on")
}

/// Returns the daemon-managed memory-feature block. The body uses `memories =
/// false` when injected inside a `[features]` table, and `features.memories =
/// false` otherwise.
fn render_cordy_memory_feature_block(in_features_table: bool) -> String {
    let mut b = String::new();
    b.push_str(CORDY_MEMORY_FEATURE_BEGIN_MARKER);
    b.push('\n');
    if in_features_table {
        b.push_str("memories = false\n");
    } else {
        b.push_str("features.memories = false\n");
    }
    b.push_str(CORDY_MEMORY_FEATURE_END_MARKER);
    b.push('\n');
    b
}

/// Returns the daemon-managed memory-config block. The body uses bare keys
/// when injected inside a `[memories]` table and dotted-key form otherwise.
fn render_cordy_memory_config_block(in_memories_table: bool) -> String {
    let mut b = String::new();
    b.push_str(CORDY_MEMORY_CONFIG_BEGIN_MARKER);
    b.push('\n');
    if in_memories_table {
        b.push_str("generate_memories = false\n");
        b.push_str("use_memories = false\n");
    } else {
        b.push_str("memories.generate_memories = false\n");
        b.push_str("memories.use_memories = false\n");
    }
    b.push_str(CORDY_MEMORY_CONFIG_END_MARKER);
    b.push('\n');
    b
}

/// Removes user-written directives that would conflict with the managed
/// blocks:
///
///   - `features.memories = ...` and `memories.{generate,use}_memories = ...`
///     at the TOML root (dotted-key form).
///   - `memories = ...` inside a top-level `[features]` table.
///   - `generate_memories = ...` / `use_memories = ...` inside a top-level
///     `[memories]` table.
///
/// Other tables (`[features.experimental]`, `[memories.advanced]`, ...) are
/// preserved untouched: they live under their own scope and don't redefine the
/// keys the managed blocks set at the root / in the canonical tables.
fn strip_user_memory_directives(content: &str) -> String {
    let mut out: Vec<&str> = Vec::with_capacity(content.lines().count());
    let mut current_table = ""; // empty = TOML root
    for line in content.split('\n') {
        let trimmed = line.trim();
        if root_features_table_header_re().is_match(line) {
            current_table = "[features]";
            out.push(line);
            continue;
        }
        if root_memories_table_header_re().is_match(line) {
            current_table = "[memories]";
            out.push(line);
            continue;
        }
        if trimmed.starts_with('[') {
            current_table = trimmed;
            out.push(line);
            continue;
        }
        match current_table {
            ""
                if root_dotted_features_memories_re().is_match(trimmed)
                    || root_dotted_memories_generate_re().is_match(trimmed)
                    || root_dotted_memories_use_re().is_match(trimmed) =>
            {
                continue;
            }
            "[features]" if features_table_memories_re().is_match(trimmed) => {
                continue;
            }
            "[memories]"
                if memories_table_generate_re().is_match(trimmed)
                    || memories_table_use_re().is_match(trimmed) =>
            {
                continue;
            }
            _ => {}
        }
        out.push(line);
    }
    out.join("\n")
}

/// Reports whether the file contains a top-level `[memories]` table header.
/// Sub-tables like `[memories.advanced]` do NOT count: they implicitly create
/// `memories` but don't conflict with a root-level
/// `memories.generate_memories` dotted key.
fn has_root_memories_table(content: &str) -> bool {
    content
        .split('\n')
        .any(|line| root_memories_table_header_re().is_match(line))
}

/// Inserts the in-table memory-feature block immediately after the first
/// `[features]` header line. Caller must have already stripped any prior
/// managed block and any user-set `memories` directive from inside the table.
fn inject_memory_feature_block_into_features_table(content: &str) -> String {
    inject_after_header(
        content,
        root_features_table_header_re(),
        &render_cordy_memory_feature_block(true),
    )
}

/// Inserts the in-table memory-config block immediately after the first
/// `[memories]` header line. Caller must have already stripped any prior
/// managed block and any user-set `generate_memories` / `use_memories`
/// directive from inside the table.
fn inject_memory_config_block_into_memories_table(content: &str) -> String {
    inject_after_header(
        content,
        root_memories_table_header_re(),
        &render_cordy_memory_config_block(true),
    )
}

/// Inserts block right after the first line matching header. Blank lines that
/// would otherwise sit between the inserted block and the next non-blank line
/// are dropped so the END marker is butted against the next table / key.
/// Without this normalization, the `\n*` quantifier in the block regexes would
/// greedily consume those blank lines on the next strip, and the rewrite would
/// no longer be byte-exact idempotent.
///
/// The trailing "" element produced by splitting when the file ends with `\n`
/// is preserved so the rewritten file keeps its EOF newline.
fn inject_after_header(content: &str, header: &Regex, block: &str) -> String {
    let block_lines: Vec<&str> = block.trim_end_matches('\n').split('\n').collect();
    let lines: Vec<&str> = content.split('\n').collect();
    for (i, line) in lines.iter().enumerate() {
        if !header.is_match(line) {
            continue;
        }
        let mut tail: &[&str] = &lines[i + 1..];
        // Drop leading blanks that follow the inserted block, but never strip
        // the lone trailing-newline marker.
        while tail.len() > 1 && tail[0].is_empty() {
            tail = &tail[1..];
        }
        let mut out: Vec<&str> = Vec::with_capacity(lines.len() + block_lines.len());
        out.extend_from_slice(&lines[..=i]);
        out.extend_from_slice(&block_lines);
        out.extend_from_slice(tail);
        return out.join("\n");
    }
    content.to_string()
}

/// Writes the daemon-managed memory blocks into the per-task config.toml so
/// Codex native memory stays disabled. Idempotent: running it twice produces
/// the same file.
///
/// When CORDY_CODEX_MEMORY is set to a truthy value, the function is a no-op —
/// the user has explicitly opted into Codex native memory and accepts the leak
/// risk. Toggling the env var across prepare runs is not supported: the
/// per-task config is short-lived (recreated per task), so users should set
/// the var once at daemon start.
pub(crate) fn ensure_codex_memory_config(config_path: &str) -> anyhow::Result<()> {
    if codex_memory_enabled() {
        tracing::info!(
            config_path = %config_path,
            "codex memory: leaving Codex native memory untouched per CORDY_CODEX_MEMORY"
        );
        return Ok(());
    }

    let data = match std::fs::read_to_string(config_path) {
        Ok(d) => d,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(anyhow::Error::new(e).context("read config.toml")),
    };
    let mut existing = data.clone();

    // Always strip any previously written managed blocks (root or in-table
    // form) so reruns and layout transitions stay clean.
    existing = memory_feature_block_re()
        .replace_all(&existing, "")
        .into_owned();
    existing = memory_config_block_re()
        .replace_all(&existing, "")
        .into_owned();
    // Strip user-set directives in every encoding; the managed blocks re-add
    // the canonical forms below.
    existing = strip_user_memory_directives(&existing);

    let has_features = has_root_features_table(&existing);
    let has_memories = has_root_memories_table(&existing);

    // In-table injections happen first so the root-prepended blocks land at
    // the very top of the file (above any user tables).
    if has_features {
        existing = inject_memory_feature_block_into_features_table(&existing);
    }
    if has_memories {
        existing = inject_memory_config_block_into_memories_table(&existing);
    }

    // Build the root-form blocks (if any) and prepend them.
    let mut prepend = String::new();
    if !has_features {
        prepend.push_str(&render_cordy_memory_feature_block(false));
    }
    if !has_memories {
        prepend.push_str(&render_cordy_memory_config_block(false));
    }

    existing = existing.trim_start_matches('\n').to_string();
    if !prepend.is_empty() {
        if existing.is_empty() {
            existing = prepend;
        } else {
            existing = format!("{prepend}\n{existing}");
        }
    }

    if existing == data {
        return Ok(());
    }

    std::fs::write(config_path, existing).context("write config.toml")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Port of TestRenderCordyMemoryBlocks: table vs dotted-key forms for both
    // managed blocks.
    #[test]
    fn test_render_cordy_memory_blocks() {
        let feat_in = render_cordy_memory_feature_block(true);
        assert!(feat_in.contains("\nmemories = false\n"));
        assert!(!feat_in.contains("features.memories"));

        let feat_root = render_cordy_memory_feature_block(false);
        assert!(feat_root.contains("\nfeatures.memories = false\n"));

        let cfg_in = render_cordy_memory_config_block(true);
        assert!(cfg_in.contains("\ngenerate_memories = false\n"));
        assert!(cfg_in.contains("\nuse_memories = false\n"));

        let cfg_root = render_cordy_memory_config_block(false);
        assert!(cfg_root.contains("\nmemories.generate_memories = false\n"));
        assert!(cfg_root.contains("\nmemories.use_memories = false\n"));
    }

    // Port of TestStripUserMemoryDirectives: all three encodings stripped per
    // scope, unrelated tables preserved.
    #[test]
    fn test_strip_user_memory_directives() {
        let input = "keep = 1\nfeatures.memories = true\nmemories.generate_memories = true\nmemories.use_memories = true\n[features]\nmemories = true\nstay = 2\n[memories]\ngenerate_memories = true\nuse_memories = true\nalso_stay = 3\n[memories.advanced]\ngenerate_memories = true\n";
        let got = strip_user_memory_directives(input);
        assert!(got.contains("keep = 1"));
        assert!(!got.contains("features.memories = true"));
        assert!(!got.contains("memories.generate_memories = true"));
        assert!(!got.lines().any(|l| l.trim() == "memories = true"));
        // The surviving generate/use lines belong only to [memories.advanced].
        assert!(got.contains("[memories.advanced]\ngenerate_memories = true"));
        let in_advanced_only = got
            .lines()
            .filter(|l| l.trim() == "generate_memories = true" || l.trim() == "use_memories = true")
            .count()
            == 1;
        assert!(in_advanced_only, "{got}");
        assert!(got.contains("stay = 2"));
        assert!(got.contains("also_stay = 3"));
        // Sub-table under [memories] keeps its own keys untouched.
        assert!(got.contains("[memories.advanced]"));
        assert!(got.matches("generate_memories = true").count() == 1);
    }

    // Port of TestHasRootMemoriesTable: sub-tables do not count.
    #[test]
    fn test_has_root_memories_table() {
        assert!(has_root_memories_table("[memories]\na = 1\n"));
        assert!(has_root_memories_table("  [memories]  # note\n"));
        assert!(!has_root_memories_table("[memories.advanced]\n"));
        assert!(!has_root_memories_table("x = 1\n"));
    }

    // Port of TestInjectAfterHeader blank-line normalization: the END marker
    // butts against the next key so the rewrite stays byte-exact idempotent.
    #[test]
    fn test_inject_after_header_normalizes_blanks() {
        let content = "[features]\n\n\nnext = 1\n";
        let injected = inject_after_header(
            content,
            root_features_table_header_re(),
            &render_cordy_memory_feature_block(true),
        );
        assert!(injected.contains("[features]\n# BEGIN"));
        assert!(injected.contains("# END cordy-managed memory-feature\nnext = 1"));

        // EOF newline preserved via the lone trailing "" split element.
        let eof = "[features]\nbody = 1\n";
        let injected = inject_after_header(
            eof,
            root_features_table_header_re(),
            &render_cordy_memory_feature_block(true),
        );
        assert!(injected.ends_with("body = 1\n"));
    }

    // Port of TestEnsureCodexMemoryConfigIdempotent + layout transitions:
    // both blocks adapt to existing tables and stay byte-stable across reruns.
    #[test]
    fn test_ensure_codex_memory_config_idempotent_and_layout_aware() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp
            .path()
            .join("config.toml")
            .to_string_lossy()
            .into_owned();

        // Fresh file: both root-form blocks prepended in order.
        ensure_codex_memory_config(&path).unwrap();
        let first = std::fs::read_to_string(&path).unwrap();
        assert!(first.starts_with(CORDY_MEMORY_FEATURE_BEGIN_MARKER));
        assert!(first.contains("features.memories = false"));
        assert!(first.contains("memories.generate_memories = false"));
        assert!(first.contains("memories.use_memories = false"));

        // Idempotent.
        ensure_codex_memory_config(&path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), first);

        // User adds both tables: blocks migrate INSIDE them.
        std::fs::write(
            &path,
            format!("{first}\n[features]\nother = 1\n[memories]\ncount = 2\n"),
        )
        .unwrap();
        ensure_codex_memory_config(&path).unwrap();
        let migrated = std::fs::read_to_string(&path).unwrap();
        assert!(migrated.contains("[features]\n# BEGIN cordy-managed memory-feature"));
        assert!(migrated.contains("\nmemories = false\n"));
        assert!(migrated.contains("[memories]\n# BEGIN cordy-managed memory-config"));
        assert!(migrated.contains("\ngenerate_memories = false\n"));
        assert!(!migrated.contains("features.memories = false"));
        assert!(!migrated.contains("memories.generate_memories = false"));

        // Idempotent in the new layout too.
        ensure_codex_memory_config(&path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), migrated);

        // User-set directives in every encoding are replaced by canonical ones.
        std::fs::write(
            &path,
            "features.memories = true\nmemories.use_memories = true\nuser = 9\n",
        )
        .unwrap();
        ensure_codex_memory_config(&path).unwrap();
        let healed = std::fs::read_to_string(&path).unwrap();
        assert!(healed.contains("features.memories = false"));
        assert!(healed.contains("memories.use_memories = false"));
        assert!(!healed.contains("= true"));
        assert!(healed.contains("user = 9"));
    }

    // Port of TestCodexMemoryEnabledEscapeHatch: truthy env values keep the
    // feature on (config left untouched).
    #[test]
    fn test_codex_memory_escape_hatch() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp
            .path()
            .join("config.toml")
            .to_string_lossy()
            .into_owned();
        std::fs::write(&path, "user = 1\n").unwrap();

        std::env::set_var(CORDY_CODEX_MEMORY_ENV, "yes");
        ensure_codex_memory_config(&path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "user = 1\n");

        std::env::set_var(CORDY_CODEX_MEMORY_ENV, "");
        ensure_codex_memory_config(&path).unwrap();
        let got = std::fs::read_to_string(&path).unwrap();
        assert!(got.contains("features.memories = false"));
        assert!(got.contains("user = 1"));

        std::env::remove_var(CORDY_CODEX_MEMORY_ENV);
    }
}
