//! Port of execenv/codex_multi_agent.go.
//!
//! Symbol map:
//! - CordyCodexMultiAgentEnv   → CORDY_CODEX_MULTI_AGENT_ENV
//! - cordyMultiAgentBegin/EndMarker → CORDY_MULTI_AGENT_BEGIN_MARKER / CORDY_MULTI_AGENT_END_MARKER
//! - multiAgentBlockRe         → multi_agent_block_re
//! - rootFeaturesTableHeaderRe → ROOT_FEATURES_TABLE_HEADER_RE (shared with
//!   codex_memory.rs, which imports it like the Go package-level var)
//! - featuresTableMultiAgentRe → features_table_multi_agent_re
//! - rootDottedMultiAgentRe    → root_dotted_multi_agent_re
//! - codexMultiAgentEnabled    → codex_multi_agent_enabled
//! - renderCordyMultiAgentBlock → render_cordy_multi_agent_block
//! - stripUserMultiAgentDirectives → strip_user_multi_agent_directives
//! - hasRootFeaturesTable      → has_root_features_table
//! - injectManagedBlockIntoFeaturesTable → inject_managed_block_into_features_table
//! - ensureCodexMultiAgentConfig → ensure_codex_multi_agent_config
//!
//! Deviations:
//! - slog logger parameter dropped; tracing macros used directly.

use anyhow::Context;
use regex::Regex;

/// Env var users can set to keep Codex native multi-agent enabled inside
/// daemon-managed tasks. Anything truthy (1, true, yes, on; case-insensitive)
/// keeps the feature on; everything else (including unset) disables it.
pub const CORDY_CODEX_MULTI_AGENT_ENV: &str = "CORDY_CODEX_MULTI_AGENT";

/// Delimit the multi-agent-specific managed block. Kept separate from the
/// sandbox block so each can evolve and migrate independently.
const CORDY_MULTI_AGENT_BEGIN_MARKER: &str =
    "# BEGIN cordy-managed multi-agent (do not edit; regenerated by daemon)";
const CORDY_MULTI_AGENT_END_MARKER: &str = "# END cordy-managed multi-agent";

/// `\n*` rather than `\n?` so reruns don't accumulate blank lines when this
/// block coexists with the sandbox managed block in the same file. The same
/// regex matches the block whether it sits at the file root (dotted-key form)
/// or inside a `[features]` table — only the body keys differ.
fn multi_agent_block_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(&format!(
            r"(?ms)^{}.*?^{}\n*",
            regex::escape(CORDY_MULTI_AGENT_BEGIN_MARKER),
            regex::escape(CORDY_MULTI_AGENT_END_MARKER)
        ))
        .expect("static regex")
    })
}

// Shared package-level regexes (codex_memory.rs imports these, mirroring how
// both Go files read the same package vars).

/// Matches a top-level `[features]` table header, allowing TOML's optional
/// whitespace inside brackets and inline comments after the header.
pub(crate) fn root_features_table_header_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*\[\s*features\s*\]\s*(?:#.*)?$").expect("static regex"))
}

/// Matches `multi_agent = ...` (with optional whitespace) inside a `[features]`
/// table.
fn features_table_multi_agent_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*multi_agent\s*=").expect("static regex"))
}

/// Matches `features.multi_agent = ...` at the TOML root (top-level dotted-key
/// form, including TOML's optional whitespace around dots).
fn root_dotted_multi_agent_re() -> &'static Regex {
    static RE: std::sync::OnceLock<Regex> = std::sync::OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*features\s*\.\s*multi_agent\s*=").expect("static regex"))
}

/// Reports whether the user opted into keeping Codex native multi-agent on for
/// daemon-managed tasks.
fn codex_multi_agent_enabled() -> bool {
    let raw = std::env::var(CORDY_CODEX_MULTI_AGENT_ENV)
        .unwrap_or_default()
        .trim()
        .to_lowercase();
    matches!(raw.as_str(), "1" | "true" | "yes" | "on")
}

/// Returns the daemon-managed multi-agent block. The body uses `multi_agent =
/// false` when injected inside a `[features]` table, and `features.multi_agent
/// = false` otherwise.
fn render_cordy_multi_agent_block(in_features_table: bool) -> String {
    let mut b = String::new();
    b.push_str(CORDY_MULTI_AGENT_BEGIN_MARKER);
    b.push('\n');
    if in_features_table {
        b.push_str("multi_agent = false\n");
    } else {
        b.push_str("features.multi_agent = false\n");
    }
    b.push_str(CORDY_MULTI_AGENT_END_MARKER);
    b.push('\n');
    b
}

/// Removes any `features.multi_agent = ...` line at the TOML root (dotted-key
/// form), plus any `multi_agent = ...` line that sits inside a top-level
/// `[features]` table. Both forms encode the same TOML key and would conflict
/// with the managed block.
///
/// Other tables (`[features.experimental]`, `[profiles.foo]`, ...) are
/// preserved untouched: they live under their own scope and don't redefine
/// `features.multi_agent` at the root.
fn strip_user_multi_agent_directives(content: &str) -> String {
    let mut out: Vec<&str> = Vec::with_capacity(content.lines().count());
    let mut current_table = ""; // empty = TOML root
    for line in content.split('\n') {
        let trimmed = line.trim();
        if root_features_table_header_re().is_match(line) {
            current_table = "[features]";
            out.push(line);
            continue;
        }
        if trimmed.starts_with('[') {
            current_table = trimmed;
            out.push(line);
            continue;
        }
        match current_table {
            "" if root_dotted_multi_agent_re().is_match(trimmed) => continue,
            "[features]" if features_table_multi_agent_re().is_match(trimmed) => continue,
            _ => {}
        }
        out.push(line);
    }
    out.join("\n")
}

/// Reports whether the file contains a top-level `[features]` table header.
/// Sub-tables like `[features.experimental]` do NOT count: they implicitly
/// create `features` but don't conflict with a root-level
/// `features.multi_agent` dotted key.
pub(crate) fn has_root_features_table(content: &str) -> bool {
    content
        .split('\n')
        .any(|line| root_features_table_header_re().is_match(line))
}

/// Inserts the in-table managed block immediately after the first `[features]`
/// header line. Caller must have already stripped any prior managed block and
/// any user-set `multi_agent` directive from inside the table.
fn inject_managed_block_into_features_table(content: &str) -> String {
    let block = render_cordy_multi_agent_block(true);
    // Drop the trailing `\n` so we don't introduce a stray blank line when
    // splicing block lines between existing lines.
    let block_lines: Vec<&str> = block.trim_end_matches('\n').split('\n').collect();
    let lines: Vec<&str> = content.split('\n').collect();
    for (i, line) in lines.iter().enumerate() {
        if !root_features_table_header_re().is_match(line) {
            continue;
        }
        let mut out: Vec<&str> = Vec::with_capacity(lines.len() + block_lines.len());
        out.extend_from_slice(&lines[..=i]);
        out.extend_from_slice(&block_lines);
        out.extend_from_slice(&lines[i + 1..]);
        return out.join("\n");
    }
    content.to_string()
}

/// Writes the daemon-managed multi-agent block into the per-task config.toml
/// so Codex native subagents stay disabled. Idempotent: running it twice
/// produces the same file.
///
/// When CORDY_CODEX_MULTI_AGENT is set to a truthy value, the function is a
/// no-op — the user has explicitly opted into Codex native subagents and
/// accepts the lifecycle risk. Toggling the env var across prepare runs is not
/// supported: the per-task config is short-lived (recreated per task), so users
/// should set the var once at daemon start.
pub(crate) fn ensure_codex_multi_agent_config(config_path: &str) -> anyhow::Result<()> {
    if codex_multi_agent_enabled() {
        tracing::info!(
            config_path = %config_path,
            "codex multi-agent: leaving Codex native multi-agent untouched per CORDY_CODEX_MULTI_AGENT"
        );
        return Ok(());
    }

    let data = match std::fs::read_to_string(config_path) {
        Ok(d) => d,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(anyhow::Error::new(e).context("read config.toml")),
    };
    let mut existing = data.clone();

    // Always strip any previously written managed block (root or in-table
    // form) so reruns and layout transitions stay clean.
    existing = multi_agent_block_re()
        .replace_all(&existing, "")
        .into_owned();
    // Strip user-set directives in both encodings; the managed block re-adds
    // the canonical form below.
    existing = strip_user_multi_agent_directives(&existing);

    let updated;
    if has_root_features_table(&existing) {
        updated = inject_managed_block_into_features_table(&existing);
    } else {
        existing = existing.trim_start_matches('\n').to_string();
        let block = render_cordy_multi_agent_block(false);
        if existing.is_empty() {
            updated = block;
        } else {
            updated = format!("{block}\n{existing}");
        }
    }

    if updated == data {
        return Ok(());
    }

    std::fs::write(config_path, updated).context("write config.toml")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn set_env(key: &str, value: &str) {
        std::env::set_var(key, value);
    }

    // Serializes tests that read/mutate CORDY_CODEX_MULTI_AGENT:
    // ensure_codex_multi_agent_config consults the env var, so parallel
    // mutation from the escape-hatch test would flip a concurrent run into a
    // no-op mid-test.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    // Port of TestRenderCordyMultiAgentBlock: table vs dotted-key forms.
    #[test]
    fn test_render_cordy_multi_agent_block() {
        let in_table = render_cordy_multi_agent_block(true);
        assert!(in_table.contains(CORDY_MULTI_AGENT_BEGIN_MARKER));
        assert!(in_table.contains("\nmulti_agent = false\n"));
        assert!(!in_table.contains("features.multi_agent"));

        let at_root = render_cordy_multi_agent_block(false);
        assert!(at_root.contains("\nfeatures.multi_agent = false\n"));
        assert!(!at_root.contains("\nmulti_agent ="));
    }

    // Port of TestStripUserMultiAgentDirectives: both encodings stripped,
    // unrelated tables preserved.
    #[test]
    fn test_strip_user_multi_agent_directives() {
        let input = "root_key = 1\nfeatures.multi_agent = true\n[features]\nmulti_agent = false\nkeep_me = 2\n[features.experimental]\nmulti_agent = true\n[profiles.x]\nshell = \"sh\"\n";
        let got = strip_user_multi_agent_directives(input);
        assert!(got.contains("root_key = 1"));
        assert!(!got.contains("features.multi_agent = true"));
        assert!(!got.lines().any(|l| l.trim() == "multi_agent = false"));
        assert!(got.contains("keep_me = 2"));
        // Sub-tables live under their own scope and are preserved untouched.
        assert!(got.contains("[features.experimental]"));
        assert!(got.contains("[profiles.x]"));
    }

    // Port of TestHasRootFeaturesTable: sub-tables do not count.
    #[test]
    fn test_has_root_features_table() {
        assert!(has_root_features_table("[features]\na = 1\n"));
        assert!(has_root_features_table("  [features]  # comment\n"));
        assert!(!has_root_features_table("[features.experimental]\n"));
        assert!(!has_root_features_table("x = 1\n"));
    }

    // Port of TestEnsureCodexMultiAgentConfigIdempotent + layout transitions:
    // root-form ↔ in-table rewrites stay byte-stable and never duplicate keys.
    #[test]
    fn test_ensure_codex_multi_agent_config_idempotent_and_layout_aware() {
        let _env_guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp
            .path()
            .join("config.toml")
            .to_string_lossy()
            .into_owned();

        // Fresh file: dotted-key block at the top.
        ensure_codex_multi_agent_config(&path).unwrap();
        let first = std::fs::read_to_string(&path).unwrap();
        assert!(first.starts_with(CORDY_MULTI_AGENT_BEGIN_MARKER));
        assert!(first.contains("features.multi_agent = false"));

        // Idempotent.
        ensure_codex_multi_agent_config(&path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), first);

        // User adds a [features] table: block migrates INSIDE the table and
        // the conflicting dotted key is gone.
        std::fs::write(&path, format!("{first}\n[features]\nother = 1\n")).unwrap();
        ensure_codex_multi_agent_config(&path).unwrap();
        let migrated = std::fs::read_to_string(&path).unwrap();
        assert!(migrated.contains("[features]\n"));
        assert!(migrated.contains("\nmulti_agent = false\n"));
        assert!(!migrated.contains("features.multi_agent = false"));

        // Idempotent in the new layout too.
        ensure_codex_multi_agent_config(&path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), migrated);

        // User-set directive inside the table is replaced by the managed one.
        std::fs::write(&path, "[features]\nmulti_agent = true\nother = 1\n").unwrap();
        ensure_codex_multi_agent_config(&path).unwrap();
        let healed = std::fs::read_to_string(&path).unwrap();
        assert!(healed.contains(CORDY_MULTI_AGENT_BEGIN_MARKER));
        assert!(!healed.contains("multi_agent = true"));
        assert!(healed.contains("other = 1"));
    }

    // Port of TestCodexMultiAgentEnabledEscapeHatch: truthy env values keep
    // the feature on (config left untouched).
    #[test]
    fn test_codex_multi_agent_escape_hatch() {
        let _env_guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp
            .path()
            .join("config.toml")
            .to_string_lossy()
            .into_owned();
        std::fs::write(&path, "user = 1\n").unwrap();

        set_env(CORDY_CODEX_MULTI_AGENT_ENV, "1");
        ensure_codex_multi_agent_config(&path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "user = 1\n");

        set_env(CORDY_CODEX_MULTI_AGENT_ENV, "TRUE");
        ensure_codex_multi_agent_config(&path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "user = 1\n");

        set_env(CORDY_CODEX_MULTI_AGENT_ENV, "");
        ensure_codex_multi_agent_config(&path).unwrap();
        let got = std::fs::read_to_string(&path).unwrap();
        assert!(got.contains("features.multi_agent = false"));
        assert!(got.contains("user = 1"));

        std::env::remove_var(CORDY_CODEX_MULTI_AGENT_ENV);
    }
}
